//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAP.Business.CheckInService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stellent.com/CheckIn/", ConfigurationName="CheckInService.CheckInSoap")]
    public interface CheckInSoap {
        
        // CODEGEN: Parameter 'CustomDocMetaData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RAP.Business.CheckInService.CheckInUniversalResponse CheckInUniversal(RAP.Business.CheckInService.CheckInUniversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckInUniversalResponse> CheckInUniversalAsync(RAP.Business.CheckInService.CheckInUniversalRequest request);
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RAP.Business.CheckInService.CheckOutResponse CheckOut(RAP.Business.CheckInService.CheckOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckOutResponse> CheckOutAsync(RAP.Business.CheckInService.CheckOutRequest request);
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RAP.Business.CheckInService.CheckOutByNameResponse CheckOutByName(RAP.Business.CheckInService.CheckOutByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckOutByNameResponse> CheckOutByNameAsync(RAP.Business.CheckInService.CheckOutByNameRequest request);
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RAP.Business.CheckInService.UndoCheckOutResponse UndoCheckOut(RAP.Business.CheckInService.UndoCheckOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.UndoCheckOutResponse> UndoCheckOutAsync(RAP.Business.CheckInService.UndoCheckOutRequest request);
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RAP.Business.CheckInService.UndoCheckOutByNameResponse UndoCheckOutByName(RAP.Business.CheckInService.UndoCheckOutByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.UndoCheckOutByNameResponse> UndoCheckOutByNameAsync(RAP.Business.CheckInService.UndoCheckOutByNameRequest request);
        
        // CODEGEN: Parameter 'CustomDocMetaData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RAP.Business.CheckInService.UpdateDocInfoResponse UpdateDocInfo(RAP.Business.CheckInService.UpdateDocInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.UpdateDocInfoResponse> UpdateDocInfoAsync(RAP.Business.CheckInService.UpdateDocInfoRequest request);
        
        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RAP.Business.CheckInService.CheckInListResponse CheckInList(RAP.Business.CheckInService.CheckInListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckInListResponse> CheckInListAsync(RAP.Business.CheckInService.CheckInListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class IdcProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckInList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dDocNameField;
        
        private string dDocTitleField;
        
        private string dDocTypeField;
        
        private string dDocAuthorField;
        
        private string dSecurityGroupField;
        
        private string dDocAccountField;
        
        private int dIDField;
        
        private bool dIDFieldSpecified;
        
        private int dRevClassIDField;
        
        private bool dRevClassIDFieldSpecified;
        
        private int dRevisionIDField;
        
        private bool dRevisionIDFieldSpecified;
        
        private string dRevLabelField;
        
        private bool dIsCheckedOutField;
        
        private bool dIsCheckedOutFieldSpecified;
        
        private string dCheckoutUserField;
        
        private string dCreateDateField;
        
        private string dInDateField;
        
        private string dOutDateField;
        
        private string dStatusField;
        
        private string dReleaseStateField;
        
        private string dFlag1Field;
        
        private string dWebExtensionField;
        
        private string dProcessingStateField;
        
        private string dMessageField;
        
        private string dReleaseDateField;
        
        private string dRendition1Field;
        
        private string dRendition2Field;
        
        private string dIndexerStateField;
        
        private string dPublishTypeField;
        
        private string dPublishStateField;
        
        private IdcProperty[] customDocMetaDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dDocName {
            get {
                return this.dDocNameField;
            }
            set {
                this.dDocNameField = value;
                this.RaisePropertyChanged("dDocName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dDocTitle {
            get {
                return this.dDocTitleField;
            }
            set {
                this.dDocTitleField = value;
                this.RaisePropertyChanged("dDocTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dDocType {
            get {
                return this.dDocTypeField;
            }
            set {
                this.dDocTypeField = value;
                this.RaisePropertyChanged("dDocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dDocAuthor {
            get {
                return this.dDocAuthorField;
            }
            set {
                this.dDocAuthorField = value;
                this.RaisePropertyChanged("dDocAuthor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string dSecurityGroup {
            get {
                return this.dSecurityGroupField;
            }
            set {
                this.dSecurityGroupField = value;
                this.RaisePropertyChanged("dSecurityGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dDocAccount {
            get {
                return this.dDocAccountField;
            }
            set {
                this.dDocAccountField = value;
                this.RaisePropertyChanged("dDocAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int dID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
                this.RaisePropertyChanged("dID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified {
            get {
                return this.dIDFieldSpecified;
            }
            set {
                this.dIDFieldSpecified = value;
                this.RaisePropertyChanged("dIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int dRevClassID {
            get {
                return this.dRevClassIDField;
            }
            set {
                this.dRevClassIDField = value;
                this.RaisePropertyChanged("dRevClassID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevClassIDSpecified {
            get {
                return this.dRevClassIDFieldSpecified;
            }
            set {
                this.dRevClassIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevClassIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int dRevisionID {
            get {
                return this.dRevisionIDField;
            }
            set {
                this.dRevisionIDField = value;
                this.RaisePropertyChanged("dRevisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified {
            get {
                return this.dRevisionIDFieldSpecified;
            }
            set {
                this.dRevisionIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevisionIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dRevLabel {
            get {
                return this.dRevLabelField;
            }
            set {
                this.dRevLabelField = value;
                this.RaisePropertyChanged("dRevLabel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool dIsCheckedOut {
            get {
                return this.dIsCheckedOutField;
            }
            set {
                this.dIsCheckedOutField = value;
                this.RaisePropertyChanged("dIsCheckedOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsCheckedOutSpecified {
            get {
                return this.dIsCheckedOutFieldSpecified;
            }
            set {
                this.dIsCheckedOutFieldSpecified = value;
                this.RaisePropertyChanged("dIsCheckedOutSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string dCheckoutUser {
            get {
                return this.dCheckoutUserField;
            }
            set {
                this.dCheckoutUserField = value;
                this.RaisePropertyChanged("dCheckoutUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string dCreateDate {
            get {
                return this.dCreateDateField;
            }
            set {
                this.dCreateDateField = value;
                this.RaisePropertyChanged("dCreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string dInDate {
            get {
                return this.dInDateField;
            }
            set {
                this.dInDateField = value;
                this.RaisePropertyChanged("dInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string dOutDate {
            get {
                return this.dOutDateField;
            }
            set {
                this.dOutDateField = value;
                this.RaisePropertyChanged("dOutDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string dStatus {
            get {
                return this.dStatusField;
            }
            set {
                this.dStatusField = value;
                this.RaisePropertyChanged("dStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string dReleaseState {
            get {
                return this.dReleaseStateField;
            }
            set {
                this.dReleaseStateField = value;
                this.RaisePropertyChanged("dReleaseState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string dFlag1 {
            get {
                return this.dFlag1Field;
            }
            set {
                this.dFlag1Field = value;
                this.RaisePropertyChanged("dFlag1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string dWebExtension {
            get {
                return this.dWebExtensionField;
            }
            set {
                this.dWebExtensionField = value;
                this.RaisePropertyChanged("dWebExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string dProcessingState {
            get {
                return this.dProcessingStateField;
            }
            set {
                this.dProcessingStateField = value;
                this.RaisePropertyChanged("dProcessingState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string dMessage {
            get {
                return this.dMessageField;
            }
            set {
                this.dMessageField = value;
                this.RaisePropertyChanged("dMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string dReleaseDate {
            get {
                return this.dReleaseDateField;
            }
            set {
                this.dReleaseDateField = value;
                this.RaisePropertyChanged("dReleaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string dRendition1 {
            get {
                return this.dRendition1Field;
            }
            set {
                this.dRendition1Field = value;
                this.RaisePropertyChanged("dRendition1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string dRendition2 {
            get {
                return this.dRendition2Field;
            }
            set {
                this.dRendition2Field = value;
                this.RaisePropertyChanged("dRendition2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string dIndexerState {
            get {
                return this.dIndexerStateField;
            }
            set {
                this.dIndexerStateField = value;
                this.RaisePropertyChanged("dIndexerState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string dPublishType {
            get {
                return this.dPublishTypeField;
            }
            set {
                this.dPublishTypeField = value;
                this.RaisePropertyChanged("dPublishType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string dPublishState {
            get {
                return this.dPublishStateField;
            }
            set {
                this.dPublishStateField = value;
                this.RaisePropertyChanged("dPublishState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public IdcProperty[] CustomDocMetaData {
            get {
                return this.customDocMetaDataField;
            }
            set {
                this.customDocMetaDataField = value;
                this.RaisePropertyChanged("CustomDocMetaData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckInListResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CheckInList[] checkInListField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CheckInList", Order=0)]
        public CheckInList[] CheckInList {
            get {
                return this.checkInListField;
            }
            set {
                this.checkInListField = value;
                this.RaisePropertyChanged("CheckInList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class StatusInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
                this.RaisePropertyChanged("statusCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class UpdateDocInfoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class UndoCheckOutByNameResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class UndoCheckOutResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckOutByNameResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckOutResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckInUniversalResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dIDField;
        
        private bool dIDFieldSpecified;
        
        private int dRevisionIDField;
        
        private bool dRevisionIDFieldSpecified;
        
        private int dRevClassIDField;
        
        private bool dRevClassIDFieldSpecified;
        
        private string dRevLabelField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int dID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
                this.RaisePropertyChanged("dID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified {
            get {
                return this.dIDFieldSpecified;
            }
            set {
                this.dIDFieldSpecified = value;
                this.RaisePropertyChanged("dIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int dRevisionID {
            get {
                return this.dRevisionIDField;
            }
            set {
                this.dRevisionIDField = value;
                this.RaisePropertyChanged("dRevisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified {
            get {
                return this.dRevisionIDFieldSpecified;
            }
            set {
                this.dRevisionIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevisionIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int dRevClassID {
            get {
                return this.dRevClassIDField;
            }
            set {
                this.dRevClassIDField = value;
                this.RaisePropertyChanged("dRevClassID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevClassIDSpecified {
            get {
                return this.dRevClassIDFieldSpecified;
            }
            set {
                this.dRevClassIDFieldSpecified = value;
                this.RaisePropertyChanged("dRevClassIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dRevLabel {
            get {
                return this.dRevLabelField;
            }
            set {
                this.dRevLabelField = value;
                this.RaisePropertyChanged("dRevLabel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public StatusInfo StatusInfo {
            get {
                return this.statusInfoField;
            }
            set {
                this.statusInfoField = value;
                this.RaisePropertyChanged("StatusInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class IdcFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInUniversal", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckInUniversalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        public string dDocTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=2)]
        public string dDocType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=3)]
        public string dDocAuthor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=4)]
        public string dSecurityGroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=5)]
        public string dDocAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] CustomDocMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=7)]
        public RAP.Business.CheckInService.IdcFile primaryFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=8)]
        public RAP.Business.CheckInService.IdcFile alternateFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] extraProps;
        
        public CheckInUniversalRequest() {
        }
        
        public CheckInUniversalRequest(string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, RAP.Business.CheckInService.IdcProperty[] CustomDocMetaData, RAP.Business.CheckInService.IdcFile primaryFile, RAP.Business.CheckInService.IdcFile alternateFile, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            this.dDocName = dDocName;
            this.dDocTitle = dDocTitle;
            this.dDocType = dDocType;
            this.dDocAuthor = dDocAuthor;
            this.dSecurityGroup = dSecurityGroup;
            this.dDocAccount = dDocAccount;
            this.CustomDocMetaData = CustomDocMetaData;
            this.primaryFile = primaryFile;
            this.alternateFile = alternateFile;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInUniversalResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckInUniversalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public RAP.Business.CheckInService.CheckInUniversalResult CheckInUniversalResult;
        
        public CheckInUniversalResponse() {
        }
        
        public CheckInUniversalResponse(RAP.Business.CheckInService.CheckInUniversalResult CheckInUniversalResult) {
            this.CheckInUniversalResult = CheckInUniversalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckOut", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public int dID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] extraProps;
        
        public CheckOutRequest() {
        }
        
        public CheckOutRequest(int dID, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            this.dID = dID;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckOutResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public RAP.Business.CheckInService.CheckOutResult CheckOutResult;
        
        public CheckOutResponse() {
        }
        
        public CheckOutResponse(RAP.Business.CheckInService.CheckOutResult CheckOutResult) {
            this.CheckOutResult = CheckOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckOutByName", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckOutByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] extraProps;
        
        public CheckOutByNameRequest() {
        }
        
        public CheckOutByNameRequest(string dDocName, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            this.dDocName = dDocName;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckOutByNameResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckOutByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public RAP.Business.CheckInService.CheckOutByNameResult CheckOutByNameResult;
        
        public CheckOutByNameResponse() {
        }
        
        public CheckOutByNameResponse(RAP.Business.CheckInService.CheckOutByNameResult CheckOutByNameResult) {
            this.CheckOutByNameResult = CheckOutByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UndoCheckOut", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UndoCheckOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public int dID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] extraProps;
        
        public UndoCheckOutRequest() {
        }
        
        public UndoCheckOutRequest(int dID, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            this.dID = dID;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UndoCheckOutResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UndoCheckOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public RAP.Business.CheckInService.UndoCheckOutResult UndoCheckOutResult;
        
        public UndoCheckOutResponse() {
        }
        
        public UndoCheckOutResponse(RAP.Business.CheckInService.UndoCheckOutResult UndoCheckOutResult) {
            this.UndoCheckOutResult = UndoCheckOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UndoCheckOutByName", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UndoCheckOutByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] extraProps;
        
        public UndoCheckOutByNameRequest() {
        }
        
        public UndoCheckOutByNameRequest(string dDocName, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            this.dDocName = dDocName;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UndoCheckOutByNameResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UndoCheckOutByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public RAP.Business.CheckInService.UndoCheckOutByNameResult UndoCheckOutByNameResult;
        
        public UndoCheckOutByNameResponse() {
        }
        
        public UndoCheckOutByNameResponse(RAP.Business.CheckInService.UndoCheckOutByNameResult UndoCheckOutByNameResult) {
            this.UndoCheckOutByNameResult = UndoCheckOutByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocInfo", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UpdateDocInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public int dID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        public string dRevLabel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=2)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=3)]
        public string dDocTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=4)]
        public string dDocType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=5)]
        public string dDocAuthor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=6)]
        public string dSecurityGroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=7)]
        public string dDocAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] CustomDocMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] extraProps;
        
        public UpdateDocInfoRequest() {
        }
        
        public UpdateDocInfoRequest(int dID, string dRevLabel, string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, RAP.Business.CheckInService.IdcProperty[] CustomDocMetaData, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            this.dID = dID;
            this.dRevLabel = dRevLabel;
            this.dDocName = dDocName;
            this.dDocTitle = dDocTitle;
            this.dDocType = dDocType;
            this.dDocAuthor = dDocAuthor;
            this.dSecurityGroup = dSecurityGroup;
            this.dDocAccount = dDocAccount;
            this.CustomDocMetaData = CustomDocMetaData;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocInfoResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UpdateDocInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public RAP.Business.CheckInService.UpdateDocInfoResult UpdateDocInfoResult;
        
        public UpdateDocInfoResponse() {
        }
        
        public UpdateDocInfoResponse(RAP.Business.CheckInService.UpdateDocInfoResult UpdateDocInfoResult) {
            this.UpdateDocInfoResult = UpdateDocInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInList", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckInListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public bool userOnly;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public RAP.Business.CheckInService.IdcProperty[] extraProps;
        
        public CheckInListRequest() {
        }
        
        public CheckInListRequest(bool userOnly, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            this.userOnly = userOnly;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInListResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckInListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public RAP.Business.CheckInService.CheckInListResult CheckInListResult;
        
        public CheckInListResponse() {
        }
        
        public CheckInListResponse(RAP.Business.CheckInService.CheckInListResult CheckInListResult) {
            this.CheckInListResult = CheckInListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckInSoapChannel : RAP.Business.CheckInService.CheckInSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckInSoapClient : System.ServiceModel.ClientBase<RAP.Business.CheckInService.CheckInSoap>, RAP.Business.CheckInService.CheckInSoap {
        
        public CheckInSoapClient() {
        }
        
        public CheckInSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckInSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckInSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckInSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RAP.Business.CheckInService.CheckInUniversalResponse RAP.Business.CheckInService.CheckInSoap.CheckInUniversal(RAP.Business.CheckInService.CheckInUniversalRequest request) {
            return base.Channel.CheckInUniversal(request);
        }
        
        public RAP.Business.CheckInService.CheckInUniversalResult CheckInUniversal(string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, RAP.Business.CheckInService.IdcProperty[] CustomDocMetaData, RAP.Business.CheckInService.IdcFile primaryFile, RAP.Business.CheckInService.IdcFile alternateFile, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.CheckInUniversalRequest inValue = new RAP.Business.CheckInService.CheckInUniversalRequest();
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.primaryFile = primaryFile;
            inValue.alternateFile = alternateFile;
            inValue.extraProps = extraProps;
            RAP.Business.CheckInService.CheckInUniversalResponse retVal = ((RAP.Business.CheckInService.CheckInSoap)(this)).CheckInUniversal(inValue);
            return retVal.CheckInUniversalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckInUniversalResponse> RAP.Business.CheckInService.CheckInSoap.CheckInUniversalAsync(RAP.Business.CheckInService.CheckInUniversalRequest request) {
            return base.Channel.CheckInUniversalAsync(request);
        }
        
        public System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckInUniversalResponse> CheckInUniversalAsync(string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, RAP.Business.CheckInService.IdcProperty[] CustomDocMetaData, RAP.Business.CheckInService.IdcFile primaryFile, RAP.Business.CheckInService.IdcFile alternateFile, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.CheckInUniversalRequest inValue = new RAP.Business.CheckInService.CheckInUniversalRequest();
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.primaryFile = primaryFile;
            inValue.alternateFile = alternateFile;
            inValue.extraProps = extraProps;
            return ((RAP.Business.CheckInService.CheckInSoap)(this)).CheckInUniversalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RAP.Business.CheckInService.CheckOutResponse RAP.Business.CheckInService.CheckInSoap.CheckOut(RAP.Business.CheckInService.CheckOutRequest request) {
            return base.Channel.CheckOut(request);
        }
        
        public RAP.Business.CheckInService.CheckOutResult CheckOut(int dID, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.CheckOutRequest inValue = new RAP.Business.CheckInService.CheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            RAP.Business.CheckInService.CheckOutResponse retVal = ((RAP.Business.CheckInService.CheckInSoap)(this)).CheckOut(inValue);
            return retVal.CheckOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckOutResponse> RAP.Business.CheckInService.CheckInSoap.CheckOutAsync(RAP.Business.CheckInService.CheckOutRequest request) {
            return base.Channel.CheckOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckOutResponse> CheckOutAsync(int dID, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.CheckOutRequest inValue = new RAP.Business.CheckInService.CheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            return ((RAP.Business.CheckInService.CheckInSoap)(this)).CheckOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RAP.Business.CheckInService.CheckOutByNameResponse RAP.Business.CheckInService.CheckInSoap.CheckOutByName(RAP.Business.CheckInService.CheckOutByNameRequest request) {
            return base.Channel.CheckOutByName(request);
        }
        
        public RAP.Business.CheckInService.CheckOutByNameResult CheckOutByName(string dDocName, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.CheckOutByNameRequest inValue = new RAP.Business.CheckInService.CheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            RAP.Business.CheckInService.CheckOutByNameResponse retVal = ((RAP.Business.CheckInService.CheckInSoap)(this)).CheckOutByName(inValue);
            return retVal.CheckOutByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckOutByNameResponse> RAP.Business.CheckInService.CheckInSoap.CheckOutByNameAsync(RAP.Business.CheckInService.CheckOutByNameRequest request) {
            return base.Channel.CheckOutByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckOutByNameResponse> CheckOutByNameAsync(string dDocName, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.CheckOutByNameRequest inValue = new RAP.Business.CheckInService.CheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            return ((RAP.Business.CheckInService.CheckInSoap)(this)).CheckOutByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RAP.Business.CheckInService.UndoCheckOutResponse RAP.Business.CheckInService.CheckInSoap.UndoCheckOut(RAP.Business.CheckInService.UndoCheckOutRequest request) {
            return base.Channel.UndoCheckOut(request);
        }
        
        public RAP.Business.CheckInService.UndoCheckOutResult UndoCheckOut(int dID, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.UndoCheckOutRequest inValue = new RAP.Business.CheckInService.UndoCheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            RAP.Business.CheckInService.UndoCheckOutResponse retVal = ((RAP.Business.CheckInService.CheckInSoap)(this)).UndoCheckOut(inValue);
            return retVal.UndoCheckOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.UndoCheckOutResponse> RAP.Business.CheckInService.CheckInSoap.UndoCheckOutAsync(RAP.Business.CheckInService.UndoCheckOutRequest request) {
            return base.Channel.UndoCheckOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<RAP.Business.CheckInService.UndoCheckOutResponse> UndoCheckOutAsync(int dID, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.UndoCheckOutRequest inValue = new RAP.Business.CheckInService.UndoCheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            return ((RAP.Business.CheckInService.CheckInSoap)(this)).UndoCheckOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RAP.Business.CheckInService.UndoCheckOutByNameResponse RAP.Business.CheckInService.CheckInSoap.UndoCheckOutByName(RAP.Business.CheckInService.UndoCheckOutByNameRequest request) {
            return base.Channel.UndoCheckOutByName(request);
        }
        
        public RAP.Business.CheckInService.UndoCheckOutByNameResult UndoCheckOutByName(string dDocName, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.UndoCheckOutByNameRequest inValue = new RAP.Business.CheckInService.UndoCheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            RAP.Business.CheckInService.UndoCheckOutByNameResponse retVal = ((RAP.Business.CheckInService.CheckInSoap)(this)).UndoCheckOutByName(inValue);
            return retVal.UndoCheckOutByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.UndoCheckOutByNameResponse> RAP.Business.CheckInService.CheckInSoap.UndoCheckOutByNameAsync(RAP.Business.CheckInService.UndoCheckOutByNameRequest request) {
            return base.Channel.UndoCheckOutByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<RAP.Business.CheckInService.UndoCheckOutByNameResponse> UndoCheckOutByNameAsync(string dDocName, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.UndoCheckOutByNameRequest inValue = new RAP.Business.CheckInService.UndoCheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            return ((RAP.Business.CheckInService.CheckInSoap)(this)).UndoCheckOutByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RAP.Business.CheckInService.UpdateDocInfoResponse RAP.Business.CheckInService.CheckInSoap.UpdateDocInfo(RAP.Business.CheckInService.UpdateDocInfoRequest request) {
            return base.Channel.UpdateDocInfo(request);
        }
        
        public RAP.Business.CheckInService.UpdateDocInfoResult UpdateDocInfo(int dID, string dRevLabel, string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, RAP.Business.CheckInService.IdcProperty[] CustomDocMetaData, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.UpdateDocInfoRequest inValue = new RAP.Business.CheckInService.UpdateDocInfoRequest();
            inValue.dID = dID;
            inValue.dRevLabel = dRevLabel;
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.extraProps = extraProps;
            RAP.Business.CheckInService.UpdateDocInfoResponse retVal = ((RAP.Business.CheckInService.CheckInSoap)(this)).UpdateDocInfo(inValue);
            return retVal.UpdateDocInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.UpdateDocInfoResponse> RAP.Business.CheckInService.CheckInSoap.UpdateDocInfoAsync(RAP.Business.CheckInService.UpdateDocInfoRequest request) {
            return base.Channel.UpdateDocInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RAP.Business.CheckInService.UpdateDocInfoResponse> UpdateDocInfoAsync(int dID, string dRevLabel, string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, RAP.Business.CheckInService.IdcProperty[] CustomDocMetaData, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.UpdateDocInfoRequest inValue = new RAP.Business.CheckInService.UpdateDocInfoRequest();
            inValue.dID = dID;
            inValue.dRevLabel = dRevLabel;
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.extraProps = extraProps;
            return ((RAP.Business.CheckInService.CheckInSoap)(this)).UpdateDocInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RAP.Business.CheckInService.CheckInListResponse RAP.Business.CheckInService.CheckInSoap.CheckInList(RAP.Business.CheckInService.CheckInListRequest request) {
            return base.Channel.CheckInList(request);
        }
        
        public RAP.Business.CheckInService.CheckInListResult CheckInList(bool userOnly, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.CheckInListRequest inValue = new RAP.Business.CheckInService.CheckInListRequest();
            inValue.userOnly = userOnly;
            inValue.extraProps = extraProps;
            RAP.Business.CheckInService.CheckInListResponse retVal = ((RAP.Business.CheckInService.CheckInSoap)(this)).CheckInList(inValue);
            return retVal.CheckInListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckInListResponse> RAP.Business.CheckInService.CheckInSoap.CheckInListAsync(RAP.Business.CheckInService.CheckInListRequest request) {
            return base.Channel.CheckInListAsync(request);
        }
        
        public System.Threading.Tasks.Task<RAP.Business.CheckInService.CheckInListResponse> CheckInListAsync(bool userOnly, RAP.Business.CheckInService.IdcProperty[] extraProps) {
            RAP.Business.CheckInService.CheckInListRequest inValue = new RAP.Business.CheckInService.CheckInListRequest();
            inValue.userOnly = userOnly;
            inValue.extraProps = extraProps;
            return ((RAP.Business.CheckInService.CheckInSoap)(this)).CheckInListAsync(inValue);
        }
    }
}
