

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAP.Business.Proxy
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.stellent.com/CheckIn/", ConfigurationName = "CheckInSoap")]
    public interface CheckInSoap
    {

        // CODEGEN: Parameter 'CustomDocMetaData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CheckInUniversalResponse CheckInUniversal(CheckInUniversalRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        System.Threading.Tasks.Task<CheckInUniversalResponse> CheckInUniversalAsync(CheckInUniversalRequest request);

        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CheckOutResponse CheckOut(CheckOutRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        System.Threading.Tasks.Task<CheckOutResponse> CheckOutAsync(CheckOutRequest request);

        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CheckOutByNameResponse CheckOutByName(CheckOutByNameRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        System.Threading.Tasks.Task<CheckOutByNameResponse> CheckOutByNameAsync(CheckOutByNameRequest request);

        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UndoCheckOutResponse UndoCheckOut(UndoCheckOutRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        System.Threading.Tasks.Task<UndoCheckOutResponse> UndoCheckOutAsync(UndoCheckOutRequest request);

        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UndoCheckOutByNameResponse UndoCheckOutByName(UndoCheckOutByNameRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        System.Threading.Tasks.Task<UndoCheckOutByNameResponse> UndoCheckOutByNameAsync(UndoCheckOutByNameRequest request);

        // CODEGEN: Parameter 'CustomDocMetaData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UpdateDocInfoResponse UpdateDocInfo(UpdateDocInfoRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        System.Threading.Tasks.Task<UpdateDocInfoResponse> UpdateDocInfoAsync(UpdateDocInfoRequest request);

        // CODEGEN: Parameter 'extraProps' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CheckInListResponse CheckInList(CheckInListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.stellent.com/CheckIn/", ReplyAction = "*")]
        System.Threading.Tasks.Task<CheckInListResponse> CheckInListAsync(CheckInListRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class IdcProperty
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class CheckInList
    {

        private string dDocNameField;

        private string dDocTitleField;

        private string dDocTypeField;

        private string dDocAuthorField;

        private string dSecurityGroupField;

        private string dDocAccountField;

        private int dIDField;

        private bool dIDFieldSpecified;

        private int dRevClassIDField;

        private bool dRevClassIDFieldSpecified;

        private int dRevisionIDField;

        private bool dRevisionIDFieldSpecified;

        private string dRevLabelField;

        private bool dIsCheckedOutField;

        private bool dIsCheckedOutFieldSpecified;

        private string dCheckoutUserField;

        private string dCreateDateField;

        private string dInDateField;

        private string dOutDateField;

        private string dStatusField;

        private string dReleaseStateField;

        private string dFlag1Field;

        private string dWebExtensionField;

        private string dProcessingStateField;

        private string dMessageField;

        private string dReleaseDateField;

        private string dRendition1Field;

        private string dRendition2Field;

        private string dIndexerStateField;

        private string dPublishTypeField;

        private string dPublishStateField;

        private IdcProperty[] customDocMetaDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string dDocName
        {
            get
            {
                return this.dDocNameField;
            }
            set
            {
                this.dDocNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string dDocTitle
        {
            get
            {
                return this.dDocTitleField;
            }
            set
            {
                this.dDocTitleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string dDocType
        {
            get
            {
                return this.dDocTypeField;
            }
            set
            {
                this.dDocTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string dDocAuthor
        {
            get
            {
                return this.dDocAuthorField;
            }
            set
            {
                this.dDocAuthorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string dSecurityGroup
        {
            get
            {
                return this.dSecurityGroupField;
            }
            set
            {
                this.dSecurityGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string dDocAccount
        {
            get
            {
                return this.dDocAccountField;
            }
            set
            {
                this.dDocAccountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public int dID
        {
            get
            {
                return this.dIDField;
            }
            set
            {
                this.dIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified
        {
            get
            {
                return this.dIDFieldSpecified;
            }
            set
            {
                this.dIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public int dRevClassID
        {
            get
            {
                return this.dRevClassIDField;
            }
            set
            {
                this.dRevClassIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevClassIDSpecified
        {
            get
            {
                return this.dRevClassIDFieldSpecified;
            }
            set
            {
                this.dRevClassIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public int dRevisionID
        {
            get
            {
                return this.dRevisionIDField;
            }
            set
            {
                this.dRevisionIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified
        {
            get
            {
                return this.dRevisionIDFieldSpecified;
            }
            set
            {
                this.dRevisionIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string dRevLabel
        {
            get
            {
                return this.dRevLabelField;
            }
            set
            {
                this.dRevLabelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public bool dIsCheckedOut
        {
            get
            {
                return this.dIsCheckedOutField;
            }
            set
            {
                this.dIsCheckedOutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsCheckedOutSpecified
        {
            get
            {
                return this.dIsCheckedOutFieldSpecified;
            }
            set
            {
                this.dIsCheckedOutFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string dCheckoutUser
        {
            get
            {
                return this.dCheckoutUserField;
            }
            set
            {
                this.dCheckoutUserField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string dCreateDate
        {
            get
            {
                return this.dCreateDateField;
            }
            set
            {
                this.dCreateDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string dInDate
        {
            get
            {
                return this.dInDateField;
            }
            set
            {
                this.dInDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string dOutDate
        {
            get
            {
                return this.dOutDateField;
            }
            set
            {
                this.dOutDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string dStatus
        {
            get
            {
                return this.dStatusField;
            }
            set
            {
                this.dStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string dReleaseState
        {
            get
            {
                return this.dReleaseStateField;
            }
            set
            {
                this.dReleaseStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string dFlag1
        {
            get
            {
                return this.dFlag1Field;
            }
            set
            {
                this.dFlag1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string dWebExtension
        {
            get
            {
                return this.dWebExtensionField;
            }
            set
            {
                this.dWebExtensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string dProcessingState
        {
            get
            {
                return this.dProcessingStateField;
            }
            set
            {
                this.dProcessingStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string dMessage
        {
            get
            {
                return this.dMessageField;
            }
            set
            {
                this.dMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string dReleaseDate
        {
            get
            {
                return this.dReleaseDateField;
            }
            set
            {
                this.dReleaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string dRendition1
        {
            get
            {
                return this.dRendition1Field;
            }
            set
            {
                this.dRendition1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string dRendition2
        {
            get
            {
                return this.dRendition2Field;
            }
            set
            {
                this.dRendition2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string dIndexerState
        {
            get
            {
                return this.dIndexerStateField;
            }
            set
            {
                this.dIndexerStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string dPublishType
        {
            get
            {
                return this.dPublishTypeField;
            }
            set
            {
                this.dPublishTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string dPublishState
        {
            get
            {
                return this.dPublishStateField;
            }
            set
            {
                this.dPublishStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 27)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] CustomDocMetaData
        {
            get
            {
                return this.customDocMetaDataField;
            }
            set
            {
                this.customDocMetaDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class CheckInListResult
    {

        private CheckInList[] checkInListField;

        private StatusInfo statusInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CheckInList", Order = 0)]
        public CheckInList[] CheckInList
        {
            get
            {
                return this.checkInListField;
            }
            set
            {
                this.checkInListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class StatusInfo
    {

        private int statusCodeField;

        private bool statusCodeFieldSpecified;

        private string statusMessageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusCodeSpecified
        {
            get
            {
                return this.statusCodeFieldSpecified;
            }
            set
            {
                this.statusCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class UpdateDocInfoResult
    {

        private StatusInfo statusInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class UndoCheckOutByNameResult
    {

        private StatusInfo statusInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class UndoCheckOutResult
    {

        private StatusInfo statusInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class CheckOutByNameResult
    {

        private StatusInfo statusInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class CheckOutResult
    {

        private StatusInfo statusInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class CheckInUniversalResult
    {

        private int dIDField;

        private bool dIDFieldSpecified;

        private int dRevisionIDField;

        private bool dRevisionIDFieldSpecified;

        private int dRevClassIDField;

        private bool dRevClassIDFieldSpecified;

        private string dRevLabelField;

        private StatusInfo statusInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int dID
        {
            get
            {
                return this.dIDField;
            }
            set
            {
                this.dIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified
        {
            get
            {
                return this.dIDFieldSpecified;
            }
            set
            {
                this.dIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int dRevisionID
        {
            get
            {
                return this.dRevisionIDField;
            }
            set
            {
                this.dRevisionIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified
        {
            get
            {
                return this.dRevisionIDFieldSpecified;
            }
            set
            {
                this.dRevisionIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int dRevClassID
        {
            get
            {
                return this.dRevClassIDField;
            }
            set
            {
                this.dRevClassIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevClassIDSpecified
        {
            get
            {
                return this.dRevClassIDFieldSpecified;
            }
            set
            {
                this.dRevClassIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string dRevLabel
        {
            get
            {
                return this.dRevLabelField;
            }
            set
            {
                this.dRevLabelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.stellent.com/CheckIn/")]
    public partial class IdcFile
    {

        private string fileNameField;

        private byte[] fileContentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
        public byte[] fileContent
        {
            get
            {
                return this.fileContentField;
            }
            set
            {
                this.fileContentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckInUniversal", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class CheckInUniversalRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public string dDocName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 1)]
        public string dDocTitle;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 2)]
        public string dDocType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 3)]
        public string dDocAuthor;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 4)]
        public string dSecurityGroup;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 5)]
        public string dDocAccount;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] CustomDocMetaData;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 7)]
        public IdcFile primaryFile;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 8)]
        public IdcFile alternateFile;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] extraProps;

        public CheckInUniversalRequest()
        {
        }

        public CheckInUniversalRequest(string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, IdcProperty[] CustomDocMetaData, IdcFile primaryFile, IdcFile alternateFile, IdcProperty[] extraProps)
        {
            this.dDocName = dDocName;
            this.dDocTitle = dDocTitle;
            this.dDocType = dDocType;
            this.dDocAuthor = dDocAuthor;
            this.dSecurityGroup = dSecurityGroup;
            this.dDocAccount = dDocAccount;
            this.CustomDocMetaData = CustomDocMetaData;
            this.primaryFile = primaryFile;
            this.alternateFile = alternateFile;
            this.extraProps = extraProps;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckInUniversalResponse", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class CheckInUniversalResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public CheckInUniversalResult CheckInUniversalResult;

        public CheckInUniversalResponse()
        {
        }

        public CheckInUniversalResponse(CheckInUniversalResult CheckInUniversalResult)
        {
            this.CheckInUniversalResult = CheckInUniversalResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckOut", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class CheckOutRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public int dID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] extraProps;

        public CheckOutRequest()
        {
        }

        public CheckOutRequest(int dID, IdcProperty[] extraProps)
        {
            this.dID = dID;
            this.extraProps = extraProps;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckOutResponse", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class CheckOutResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public CheckOutResult CheckOutResult;

        public CheckOutResponse()
        {
        }

        public CheckOutResponse(CheckOutResult CheckOutResult)
        {
            this.CheckOutResult = CheckOutResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckOutByName", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class CheckOutByNameRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public string dDocName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] extraProps;

        public CheckOutByNameRequest()
        {
        }

        public CheckOutByNameRequest(string dDocName, IdcProperty[] extraProps)
        {
            this.dDocName = dDocName;
            this.extraProps = extraProps;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckOutByNameResponse", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class CheckOutByNameResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public CheckOutByNameResult CheckOutByNameResult;

        public CheckOutByNameResponse()
        {
        }

        public CheckOutByNameResponse(CheckOutByNameResult CheckOutByNameResult)
        {
            this.CheckOutByNameResult = CheckOutByNameResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UndoCheckOut", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class UndoCheckOutRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public int dID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] extraProps;

        public UndoCheckOutRequest()
        {
        }

        public UndoCheckOutRequest(int dID, IdcProperty[] extraProps)
        {
            this.dID = dID;
            this.extraProps = extraProps;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UndoCheckOutResponse", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class UndoCheckOutResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public UndoCheckOutResult UndoCheckOutResult;

        public UndoCheckOutResponse()
        {
        }

        public UndoCheckOutResponse(UndoCheckOutResult UndoCheckOutResult)
        {
            this.UndoCheckOutResult = UndoCheckOutResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UndoCheckOutByName", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class UndoCheckOutByNameRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public string dDocName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] extraProps;

        public UndoCheckOutByNameRequest()
        {
        }

        public UndoCheckOutByNameRequest(string dDocName, IdcProperty[] extraProps)
        {
            this.dDocName = dDocName;
            this.extraProps = extraProps;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UndoCheckOutByNameResponse", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class UndoCheckOutByNameResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public UndoCheckOutByNameResult UndoCheckOutByNameResult;

        public UndoCheckOutByNameResponse()
        {
        }

        public UndoCheckOutByNameResponse(UndoCheckOutByNameResult UndoCheckOutByNameResult)
        {
            this.UndoCheckOutByNameResult = UndoCheckOutByNameResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateDocInfo", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class UpdateDocInfoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public int dID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 1)]
        public string dRevLabel;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 2)]
        public string dDocName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 3)]
        public string dDocTitle;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 4)]
        public string dDocType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 5)]
        public string dDocAuthor;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 6)]
        public string dSecurityGroup;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 7)]
        public string dDocAccount;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] CustomDocMetaData;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] extraProps;

        public UpdateDocInfoRequest()
        {
        }

        public UpdateDocInfoRequest(int dID, string dRevLabel, string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, IdcProperty[] CustomDocMetaData, IdcProperty[] extraProps)
        {
            this.dID = dID;
            this.dRevLabel = dRevLabel;
            this.dDocName = dDocName;
            this.dDocTitle = dDocTitle;
            this.dDocType = dDocType;
            this.dDocAuthor = dDocAuthor;
            this.dSecurityGroup = dSecurityGroup;
            this.dDocAccount = dDocAccount;
            this.CustomDocMetaData = CustomDocMetaData;
            this.extraProps = extraProps;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateDocInfoResponse", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class UpdateDocInfoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public UpdateDocInfoResult UpdateDocInfoResult;

        public UpdateDocInfoResponse()
        {
        }

        public UpdateDocInfoResponse(UpdateDocInfoResult UpdateDocInfoResult)
        {
            this.UpdateDocInfoResult = UpdateDocInfoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckInList", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class CheckInListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public bool userOnly;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
        public IdcProperty[] extraProps;

        public CheckInListRequest()
        {
        }

        public CheckInListRequest(bool userOnly, IdcProperty[] extraProps)
        {
            this.userOnly = userOnly;
            this.extraProps = extraProps;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CheckInListResponse", WrapperNamespace = "http://www.stellent.com/CheckIn/", IsWrapped = true)]
    public partial class CheckInListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.stellent.com/CheckIn/", Order = 0)]
        public CheckInListResult CheckInListResult;

        public CheckInListResponse()
        {
        }

        public CheckInListResponse(CheckInListResult CheckInListResult)
        {
            this.CheckInListResult = CheckInListResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckInSoapChannel : CheckInSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckInSoapClient : System.ServiceModel.ClientBase<CheckInSoap>, CheckInSoap
    {

        public CheckInSoapClient()
        {
        }

        public CheckInSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CheckInSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CheckInSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CheckInSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckInUniversalResponse CheckInSoap.CheckInUniversal(CheckInUniversalRequest request)
        {
            return base.Channel.CheckInUniversal(request);
        }

        public CheckInUniversalResult CheckInUniversal(string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, IdcProperty[] CustomDocMetaData, IdcFile primaryFile, IdcFile alternateFile, IdcProperty[] extraProps)
        {
            CheckInUniversalRequest inValue = new CheckInUniversalRequest();
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.primaryFile = primaryFile;
            inValue.alternateFile = alternateFile;
            inValue.extraProps = extraProps;
            CheckInUniversalResponse retVal = ((CheckInSoap)(this)).CheckInUniversal(inValue);
            return retVal.CheckInUniversalResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CheckInUniversalResponse> CheckInSoap.CheckInUniversalAsync(CheckInUniversalRequest request)
        {
            return base.Channel.CheckInUniversalAsync(request);
        }

        public System.Threading.Tasks.Task<CheckInUniversalResponse> CheckInUniversalAsync(string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, IdcProperty[] CustomDocMetaData, IdcFile primaryFile, IdcFile alternateFile, IdcProperty[] extraProps)
        {
            CheckInUniversalRequest inValue = new CheckInUniversalRequest();
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.primaryFile = primaryFile;
            inValue.alternateFile = alternateFile;
            inValue.extraProps = extraProps;
            return ((CheckInSoap)(this)).CheckInUniversalAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckOutResponse CheckInSoap.CheckOut(CheckOutRequest request)
        {
            return base.Channel.CheckOut(request);
        }

        public CheckOutResult CheckOut(int dID, IdcProperty[] extraProps)
        {
            CheckOutRequest inValue = new CheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            CheckOutResponse retVal = ((CheckInSoap)(this)).CheckOut(inValue);
            return retVal.CheckOutResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CheckOutResponse> CheckInSoap.CheckOutAsync(CheckOutRequest request)
        {
            return base.Channel.CheckOutAsync(request);
        }

        public System.Threading.Tasks.Task<CheckOutResponse> CheckOutAsync(int dID, IdcProperty[] extraProps)
        {
            CheckOutRequest inValue = new CheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            return ((CheckInSoap)(this)).CheckOutAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckOutByNameResponse CheckInSoap.CheckOutByName(CheckOutByNameRequest request)
        {
            return base.Channel.CheckOutByName(request);
        }

        public CheckOutByNameResult CheckOutByName(string dDocName, IdcProperty[] extraProps)
        {
            CheckOutByNameRequest inValue = new CheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            CheckOutByNameResponse retVal = ((CheckInSoap)(this)).CheckOutByName(inValue);
            return retVal.CheckOutByNameResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CheckOutByNameResponse> CheckInSoap.CheckOutByNameAsync(CheckOutByNameRequest request)
        {
            return base.Channel.CheckOutByNameAsync(request);
        }

        public System.Threading.Tasks.Task<CheckOutByNameResponse> CheckOutByNameAsync(string dDocName, IdcProperty[] extraProps)
        {
            CheckOutByNameRequest inValue = new CheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            return ((CheckInSoap)(this)).CheckOutByNameAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UndoCheckOutResponse CheckInSoap.UndoCheckOut(UndoCheckOutRequest request)
        {
            return base.Channel.UndoCheckOut(request);
        }

        public UndoCheckOutResult UndoCheckOut(int dID, IdcProperty[] extraProps)
        {
            UndoCheckOutRequest inValue = new UndoCheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            UndoCheckOutResponse retVal = ((CheckInSoap)(this)).UndoCheckOut(inValue);
            return retVal.UndoCheckOutResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UndoCheckOutResponse> CheckInSoap.UndoCheckOutAsync(UndoCheckOutRequest request)
        {
            return base.Channel.UndoCheckOutAsync(request);
        }

        public System.Threading.Tasks.Task<UndoCheckOutResponse> UndoCheckOutAsync(int dID, IdcProperty[] extraProps)
        {
            UndoCheckOutRequest inValue = new UndoCheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            return ((CheckInSoap)(this)).UndoCheckOutAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UndoCheckOutByNameResponse CheckInSoap.UndoCheckOutByName(UndoCheckOutByNameRequest request)
        {
            return base.Channel.UndoCheckOutByName(request);
        }

        public UndoCheckOutByNameResult UndoCheckOutByName(string dDocName, IdcProperty[] extraProps)
        {
            UndoCheckOutByNameRequest inValue = new UndoCheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            UndoCheckOutByNameResponse retVal = ((CheckInSoap)(this)).UndoCheckOutByName(inValue);
            return retVal.UndoCheckOutByNameResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UndoCheckOutByNameResponse> CheckInSoap.UndoCheckOutByNameAsync(UndoCheckOutByNameRequest request)
        {
            return base.Channel.UndoCheckOutByNameAsync(request);
        }

        public System.Threading.Tasks.Task<UndoCheckOutByNameResponse> UndoCheckOutByNameAsync(string dDocName, IdcProperty[] extraProps)
        {
            UndoCheckOutByNameRequest inValue = new UndoCheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            return ((CheckInSoap)(this)).UndoCheckOutByNameAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpdateDocInfoResponse CheckInSoap.UpdateDocInfo(UpdateDocInfoRequest request)
        {
            return base.Channel.UpdateDocInfo(request);
        }

        public UpdateDocInfoResult UpdateDocInfo(int dID, string dRevLabel, string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, IdcProperty[] CustomDocMetaData, IdcProperty[] extraProps)
        {
            UpdateDocInfoRequest inValue = new UpdateDocInfoRequest();
            inValue.dID = dID;
            inValue.dRevLabel = dRevLabel;
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.extraProps = extraProps;
            UpdateDocInfoResponse retVal = ((CheckInSoap)(this)).UpdateDocInfo(inValue);
            return retVal.UpdateDocInfoResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpdateDocInfoResponse> CheckInSoap.UpdateDocInfoAsync(UpdateDocInfoRequest request)
        {
            return base.Channel.UpdateDocInfoAsync(request);
        }

        public System.Threading.Tasks.Task<UpdateDocInfoResponse> UpdateDocInfoAsync(int dID, string dRevLabel, string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, IdcProperty[] CustomDocMetaData, IdcProperty[] extraProps)
        {
            UpdateDocInfoRequest inValue = new UpdateDocInfoRequest();
            inValue.dID = dID;
            inValue.dRevLabel = dRevLabel;
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.extraProps = extraProps;
            return ((CheckInSoap)(this)).UpdateDocInfoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckInListResponse CheckInSoap.CheckInList(CheckInListRequest request)
        {
            return base.Channel.CheckInList(request);
        }

        public CheckInListResult CheckInList(bool userOnly, IdcProperty[] extraProps)
        {
            CheckInListRequest inValue = new CheckInListRequest();
            inValue.userOnly = userOnly;
            inValue.extraProps = extraProps;
            CheckInListResponse retVal = ((CheckInSoap)(this)).CheckInList(inValue);
            return retVal.CheckInListResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CheckInListResponse> CheckInSoap.CheckInListAsync(CheckInListRequest request)
        {
            return base.Channel.CheckInListAsync(request);
        }

        public System.Threading.Tasks.Task<CheckInListResponse> CheckInListAsync(bool userOnly, IdcProperty[] extraProps)
        {
            CheckInListRequest inValue = new CheckInListRequest();
            inValue.userOnly = userOnly;
            inValue.extraProps = extraProps;
            return ((CheckInSoap)(this)).CheckInListAsync(inValue);
        }
    }
}

