//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAP.Core.FinServices.LogService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogDetails", Namespace="http://health.dohmh.nycnet/fsaservices/datacontracts")]
    public partial class LogDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ActionField;
        
        private int ElapsedTimeField;
        
        private string ExceptionDetailsField;
        
        private long IdField;
        
        private string MessageField;
        
        private string MessageDetailsField;
        
        private bool NotificationSentField;
        
        private RAP.Core.FinServices.LogService.RequesterDetails RequesterDetailsField;
        
        private bool SendNotificationField;
        
        private string SeverityField;
        
        private System.DateTime TimestampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElapsedTime
        {
            get
            {
                return this.ElapsedTimeField;
            }
            set
            {
                this.ElapsedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionDetails
        {
            get
            {
                return this.ExceptionDetailsField;
            }
            set
            {
                this.ExceptionDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDetails
        {
            get
            {
                return this.MessageDetailsField;
            }
            set
            {
                this.MessageDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotificationSent
        {
            get
            {
                return this.NotificationSentField;
            }
            set
            {
                this.NotificationSentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RAP.Core.FinServices.LogService.RequesterDetails RequesterDetails
        {
            get
            {
                return this.RequesterDetailsField;
            }
            set
            {
                this.RequesterDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendNotification
        {
            get
            {
                return this.SendNotificationField;
            }
            set
            {
                this.SendNotificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequesterDetails", Namespace="http://health.dohmh.nycnet/fsaservices/datacontracts")]
    public partial class RequesterDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ApplicationIdField;
        
        private string CorrelationIdField;
        
        private string DomainField;
        
        private int EmployeeNoField;
        
        private string MachineNameField;
        
        private string ProcessNameField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId
        {
            get
            {
                return this.CorrelationIdField;
            }
            set
            {
                this.CorrelationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeNo
        {
            get
            {
                return this.EmployeeNoField;
            }
            set
            {
                this.EmployeeNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName
        {
            get
            {
                return this.MachineNameField;
            }
            set
            {
                this.MachineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessName
        {
            get
            {
                return this.ProcessNameField;
            }
            set
            {
                this.ProcessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://health.dohmh.nycnet/fsaservices/datacontracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAP.Core.FinServices.LogService.RetrieveLogsResponse))]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private RAP.Core.FinServices.LogService.ResponseMessage[] MessagesField;
        
        private string StatusCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RAP.Core.FinServices.LogService.ResponseMessage[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveLogsResponse", Namespace="http://health.dohmh.nycnet/fsaservices/datacontracts")]
    public partial class RetrieveLogsResponse : RAP.Core.FinServices.LogService.ServiceResponse
    {
        
        private RAP.Core.FinServices.LogService.LogDetails[] LogsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RAP.Core.FinServices.LogService.LogDetails[] Logs
        {
            get
            {
                return this.LogsField;
            }
            set
            {
                this.LogsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://health.dohmh.nycnet/fsaservices/datacontracts")]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string MessageCodeField;
        
        private string MessageTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode
        {
            get
            {
                return this.MessageCodeField;
            }
            set
            {
                this.MessageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paging", Namespace="http://health.dohmh.nycnet/fsaservices/datacontracts")]
    public partial class Paging : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageCountField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        private int TotalCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageCount
        {
            get
            {
                return this.PageCountField;
            }
            set
            {
                this.PageCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://health.dohmh.nycnet/fsaservices/services", ConfigurationName="RAP.Core.FinServices.LogService.ILogService")]
    public interface ILogService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.dohmh.nycnet/fsaservices/services/ILogService/Ping", ReplyAction="http://health.dohmh.nycnet/fsaservices/services/ILogService/PingResponse")]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.dohmh.nycnet/fsaservices/services/ILogService/Ping", ReplyAction="http://health.dohmh.nycnet/fsaservices/services/ILogService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.dohmh.nycnet/fsaservices/services/ILogService/CreateLogEntry", ReplyAction="http://health.dohmh.nycnet/fsaservices/services/ILogService/CreateLogEntryRespons" +
            "e")]
        RAP.Core.FinServices.LogService.ServiceResponse CreateLogEntry(RAP.Core.FinServices.LogService.LogDetails logDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.dohmh.nycnet/fsaservices/services/ILogService/CreateLogEntry", ReplyAction="http://health.dohmh.nycnet/fsaservices/services/ILogService/CreateLogEntryRespons" +
            "e")]
        System.Threading.Tasks.Task<RAP.Core.FinServices.LogService.ServiceResponse> CreateLogEntryAsync(RAP.Core.FinServices.LogService.LogDetails logDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.dohmh.nycnet/fsaservices/services/ILogService/RetrieveLogEntries", ReplyAction="http://health.dohmh.nycnet/fsaservices/services/ILogService/RetrieveLogEntriesRes" +
            "ponse")]
        RAP.Core.FinServices.LogService.RetrieveLogsResponse RetrieveLogEntries(RAP.Core.FinServices.LogService.RequesterDetails requesterDetails, RAP.Core.FinServices.LogService.LogDetails searchCriteria, RAP.Core.FinServices.LogService.Paging pagingCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.dohmh.nycnet/fsaservices/services/ILogService/RetrieveLogEntries", ReplyAction="http://health.dohmh.nycnet/fsaservices/services/ILogService/RetrieveLogEntriesRes" +
            "ponse")]
        System.Threading.Tasks.Task<RAP.Core.FinServices.LogService.RetrieveLogsResponse> RetrieveLogEntriesAsync(RAP.Core.FinServices.LogService.RequesterDetails requesterDetails, RAP.Core.FinServices.LogService.LogDetails searchCriteria, RAP.Core.FinServices.LogService.Paging pagingCriteria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogServiceChannel : RAP.Core.FinServices.LogService.ILogService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogServiceClient : System.ServiceModel.ClientBase<RAP.Core.FinServices.LogService.ILogService>, RAP.Core.FinServices.LogService.ILogService
    {
        
        public LogServiceClient()
        {
        }
        
        public LogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public LogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string Ping()
        {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<string> PingAsync()
        {
            return base.Channel.PingAsync();
        }
        
        public RAP.Core.FinServices.LogService.ServiceResponse CreateLogEntry(RAP.Core.FinServices.LogService.LogDetails logDetails)
        {
            return base.Channel.CreateLogEntry(logDetails);
        }
        
        public System.Threading.Tasks.Task<RAP.Core.FinServices.LogService.ServiceResponse> CreateLogEntryAsync(RAP.Core.FinServices.LogService.LogDetails logDetails)
        {
            return base.Channel.CreateLogEntryAsync(logDetails);
        }
        
        public RAP.Core.FinServices.LogService.RetrieveLogsResponse RetrieveLogEntries(RAP.Core.FinServices.LogService.RequesterDetails requesterDetails, RAP.Core.FinServices.LogService.LogDetails searchCriteria, RAP.Core.FinServices.LogService.Paging pagingCriteria)
        {
            return base.Channel.RetrieveLogEntries(requesterDetails, searchCriteria, pagingCriteria);
        }
        
        public System.Threading.Tasks.Task<RAP.Core.FinServices.LogService.RetrieveLogsResponse> RetrieveLogEntriesAsync(RAP.Core.FinServices.LogService.RequesterDetails requesterDetails, RAP.Core.FinServices.LogService.LogDetails searchCriteria, RAP.Core.FinServices.LogService.Paging pagingCriteria)
        {
            return base.Channel.RetrieveLogEntriesAsync(requesterDetails, searchCriteria, pagingCriteria);
        }
    }
}
