<?xml version="1.0" encoding="utf-8"?><Database Name="OAKRAP" Class="AccountManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ev-sql-dev;Initial Catalog=OAKRAP;Integrated Security=True" SettingsObjectName="RAP.DAL.Properties.Settings" SettingsPropertyName="OAKRAPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserType" Member="UserTypes">
    <Type Name="UserType">
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReturnAccountSearch" Member="ReturnAccountSearches">
    <Type Name="ReturnAccountSearch" Id="ID1">
      <Column Name="RankNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AcctTypeDesc" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NotificationPreference" Member="NotificationPreferences">
    <Type Name="NotificationPreference">
      <Column Name="NotificationPreferenceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmailNotification" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MailNotification" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThirdPartyRepresentation" Member="ThirdPartyRepresentations">
    <Type Name="ThirdPartyRepresentation">
      <Column Name="ThirdPartyRepresentationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmailNotification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MailNotification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CustomerDetail_ThirdPartyRepresentation" Member="CustomerDetail" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThirdPartyCaseAssignment" Member="ThirdPartyCaseAssignments">
    <Type Name="ThirdPartyCaseAssignment">
      <Column Name="ThirdPartyCaseAssignment" Member="ThirdPartyCaseAssignment1" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CaseAssignedToThirdParty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CustomerDetail_ThirdPartyCaseAssignment" Member="CustomerDetail" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CollaboratorAccess" Member="CollaboratorAccesses">
    <Type Name="CollaboratorAccess">
      <Column Name="CollaboratorAccessID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CollaboratorCustID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="C_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="CustomerDetail_CollaboratorAccess" Member="CustomerDetail" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerDetail" IsForeignKey="true" />
      <Association Name="CustomerDetail_CollaboratorAccess1" Member="CustomerDetail1" ThisKey="CollaboratorCustID" OtherKey="CustomerID" Type="CustomerDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MailingAddress" Member="MailingAddresses">
    <Type Name="MailingAddress">
      <Column Name="MailingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine1" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CustomerDetail_MailingAddress" Member="CustomerDetail" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerDetails" Member="CustomerDetails">
    <Type Name="CustomerDetail">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustomerIdentityKey" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="bMailingAddress" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bParcelAddress" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CustomerDetail_ThirdPartyRepresentation" Member="ThirdPartyRepresentation" ThisKey="CustomerID" OtherKey="CustomerID" Type="ThirdPartyRepresentation" Cardinality="One" />
      <Association Name="CustomerDetail_ThirdPartyCaseAssignment" Member="ThirdPartyCaseAssignments" ThisKey="CustomerID" OtherKey="CustomerID" Type="ThirdPartyCaseAssignment" />
      <Association Name="CustomerDetail_CollaboratorAccess" Member="CollaboratorAccesses" ThisKey="CustomerID" OtherKey="CustomerID" Type="CollaboratorAccess" />
      <Association Name="CustomerDetail_CollaboratorAccess1" Member="CollaboratorAccesses1" ThisKey="CustomerID" OtherKey="CollaboratorCustID" Type="CollaboratorAccess" />
      <Association Name="CustomerDetail_MailingAddress" Member="MailingAddresses" ThisKey="CustomerID" OtherKey="CustomerID" Type="MailingAddress" />
      <Association Name="CustomerDetail_CustomerDetail" Member="CustomerDetail2" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerDetail" Cardinality="One" />
      <Association Name="CustomerDetail_CustomerDetail" Member="CustomerDetail1" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CityUserAccount" Member="CityUserAccounts">
    <Type Name="CityUserAccount">
      <Column Name="CityUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CityAccountTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsAnalyst" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHearingOfficer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsNonRAPStaff" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsAdminAssistant" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCityAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="OfficeLocation" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="OfficePhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MobilePhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CityAccountType_CityUserAccount" Member="CityAccountType" ThisKey="CityAccountTypeID" OtherKey="CityAccountTypeID" Type="CityAccountType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CityAccountType" Member="CityAccountTypes">
    <Type Name="CityAccountType">
      <Column Name="CityAccountTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityAccountTypeDesc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PermissionToAccountTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CityAccountType_CityUserAccount" Member="CityUserAccounts" ThisKey="CityAccountTypeID" OtherKey="CityAccountTypeID" Type="CityUserAccount" />
    </Type>
  </Table>
  <Function Name="dbo.USP_SearchAccount_Get" Method="USP_SearchAccount_Get">
    <Parameter Name="AcctType" Parameter="acctType" Type="System.Int32" DbType="Int" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(35)" />
    <Parameter Name="APNNumber" Parameter="aPNNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AddressLine1" Parameter="addressLine1" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="AddressLine2" Parameter="addressLine2" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="SortBy" Parameter="sortBy" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortReverse" Parameter="sortReverse" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentPage" Parameter="currentPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalCount" Parameter="totalCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="VarChar(MAX)" Direction="InOut" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>