<?xml version="1.0" encoding="utf-8"?><Database Name="OAKRAP" Class="ApplicationProcessingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ev-sql-dev;Initial Catalog=OAKRAP;Integrated Security=True" SettingsObjectName="RAP.DAL.Properties.Settings" SettingsPropertyName="OAKRAPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CurrentOnRentStatus" Member="CurrentOnRentStatus">
    <Type Name="CurrentOnRentStatus">
      <Column Name="RentStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RentStatus" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PetitionGrounds" Member="PetitionGrounds">
    <Type Name="PetitionGround">
      <Column Name="PetitionGroundID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PetitionDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="PetitionGround_TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos" ThisKey="PetitionGroundID" OtherKey="PetitionGroundID" Type="TenantPetitionGroundInfo" />
    </Type>
  </Table>
  <Table Name="dbo.UnitType" Member="UnitTypes">
    <Type Name="UnitType">
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="UnitType_TenantPetitionInfo" Member="TenantPetitionInfos" ThisKey="UnitTypeID" OtherKey="UnitTypeID" Type="TenantPetitionInfo" />
    </Type>
  </Table>
  <Table Name="dbo.PetitionDetails" Member="PetitionDetails">
    <Type Name="PetitionDetail">
      <Column Name="PetitionFileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerPetitionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PetitionDetail_CaseDetail" Member="CaseDetails" ThisKey="PetitionFileID" OtherKey="PetitionFileID" Type="CaseDetail" />
    </Type>
  </Table>
  <Table Name="dbo.TenantPetitionInfo" Member="TenantPetitionInfos">
    <Type Name="TenantPetitionInfo">
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumberOfUnits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RentStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LegalWithHoldingExplanation" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="bCitationDocUnavailable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MoveInDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InitialRent" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="bRAPNoticeGiven" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RAPNoticeGivnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bRentControlledByAgency" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bPetitionFiledPrviously" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PreviousCaseIDs" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="bLostService" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bSeriousProblem" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TenantPetitionInfo_TenantProblemInfo" Member="TenantProblemInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantProblemInfo" />
      <Association Name="TenantPetitionInfo_TenantLostServiceInfo" Member="TenantLostServiceInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantLostServiceInfo" />
      <Association Name="TenantPetitionInfo_TenantRentalIncrementInfo" Member="TenantRentalIncrementInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantRentalIncrementInfo" />
      <Association Name="TenantPetitionInfo_TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionGroundInfo" />
      <Association Name="UnitType_TenantPetitionInfo" Member="UnitType" ThisKey="UnitTypeID" OtherKey="UnitTypeID" Type="UnitType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantProblemInfo" Member="TenantProblemInfos">
    <Type Name="TenantProblemInfo">
      <Column Name="ProblemInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProblemDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EstimatedLoss" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="ProblemBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PayingToProblemBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TenantPetitionInfo_TenantProblemInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserInfo" Member="UserInfos">
    <Type Name="UserInfo">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine1" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="UserInfo_CaseDetail" Member="CaseDetails" ThisKey="UserID" OtherKey="OwnerUserID" Type="CaseDetail" />
      <Association Name="UserInfo_CaseDetail1" Member="CaseDetails1" ThisKey="UserID" OtherKey="TenantUserID" Type="CaseDetail" />
      <Association Name="UserInfo_CaseDetail2" Member="CaseDetails2" ThisKey="UserID" OtherKey="ThirdPartyUserID" Type="CaseDetail" />
    </Type>
  </Table>
  <Table Name="dbo.TenantLostServiceInfo" Member="TenantLostServiceInfos">
    <Type Name="TenantLostServiceInfo">
      <Column Name="LostServiceInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReducedServiceDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EstimatedLoss" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="LossBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PayingToServiceBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TenantPetitionInfo_TenantLostServiceInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CaseDetails" Member="CaseDetails">
    <Type Name="CaseDetail">
      <Column Name="C_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CaseID" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PetitionFileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PetitionCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenantUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bThirdPartyRepresentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bAgreeToCityMediation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CaseFiledBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bCaseFiledByThirdParty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CaseAssignedTo" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CityUserFirstName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CityUserLastName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CityUserMailID" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="WorlFlowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HearingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AppealDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PetitionDetail_CaseDetail" Member="PetitionDetail" ThisKey="PetitionFileID" OtherKey="PetitionFileID" Type="PetitionDetail" IsForeignKey="true" />
      <Association Name="UserInfo_CaseDetail" Member="UserInfo" ThisKey="OwnerUserID" OtherKey="UserID" Type="UserInfo" IsForeignKey="true" />
      <Association Name="UserInfo_CaseDetail1" Member="UserInfo1" ThisKey="TenantUserID" OtherKey="UserID" Type="UserInfo" IsForeignKey="true" />
      <Association Name="UserInfo_CaseDetail2" Member="UserInfo2" ThisKey="ThirdPartyUserID" OtherKey="UserID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantRentalIncrementInfo" Member="TenantRentalIncrementInfos">
    <Type Name="TenantRentalIncrementInfo">
      <Column Name="RentalIncreaseInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bRentIncreaseNoticeGiven" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentIncreaseNoticeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreaseEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreasedFrom" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="RentIncreasedTo" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="bRentIncreaseContested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TenantPetitionInfo_TenantRentalIncrementInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos">
    <Type Name="TenantPetitionGroundInfo">
      <Column Name="TenantPetitionGroudID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PetitionGroundID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PetitionGround_TenantPetitionGroundInfo" Member="PetitionGround" ThisKey="PetitionGroundID" OtherKey="PetitionGroundID" Type="PetitionGround" IsForeignKey="true" />
      <Association Name="TenantPetitionInfo_TenantPetitionGroundInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
</Database>