<?xml version="1.0" encoding="utf-8"?><Database Name="OAKRAP" Class="ApplicationProcessingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ev-sql-dev;Initial Catalog=OAKRAP;Integrated Security=True" SettingsObjectName="RAP.DAL.Properties.Settings" SettingsPropertyName="OAKRAPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CurrentOnRentStatus" Member="CurrentOnRentStatus">
    <Type Name="CurrentOnRentStatus">
      <Column Name="RentStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RentStatus" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PetitionGrounds" Member="PetitionGrounds">
    <Type Name="PetitionGround">
      <Column Name="PetitionGroundID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PetitionDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="PetitionGround_TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos" ThisKey="PetitionGroundID" OtherKey="PetitionGroundID" Type="TenantPetitionGroundInfo" />
    </Type>
  </Table>
  <Table Name="dbo.UnitType" Member="UnitTypes">
    <Type Name="UnitType">
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="UnitType_TenantPetitionInfo" Member="TenantPetitionInfos" ThisKey="UnitTypeID" OtherKey="UnitTypeID" Type="TenantPetitionInfo" />
    </Type>
  </Table>
  <Table Name="dbo.PetitionDetails" Member="PetitionDetails">
    <Type Name="PetitionDetail">
      <Column Name="PetitionFileID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerPetitionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantProblemInfo" Member="TenantProblemInfos">
    <Type Name="TenantProblemInfo">
      <Column Name="ProblemInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProblemDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EstimatedLoss" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="ProblemBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PayingToProblemBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TenantPetitionInfo_TenantProblemInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantLostServiceInfo" Member="TenantLostServiceInfos">
    <Type Name="TenantLostServiceInfo">
      <Column Name="LostServiceInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReducedServiceDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EstimatedLoss" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="LossBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PayingToServiceBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TenantPetitionInfo_TenantLostServiceInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos">
    <Type Name="TenantPetitionGroundInfo">
      <Column Name="TenantPetitionGroudID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PetitionGroundID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PetitionGround_TenantPetitionGroundInfo" Member="PetitionGround" ThisKey="PetitionGroundID" OtherKey="PetitionGroundID" Type="PetitionGround" IsForeignKey="true" />
      <Association Name="TenantPetitionInfo_TenantPetitionGroundInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantPetitionInfo" Member="TenantPetitionInfos">
    <Type Name="TenantPetitionInfo">
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumberOfUnits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RentStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LegalWithHoldingExplanation" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="bCitationDocUnavailable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MoveInDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InitialRent" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="bRAPNoticeGiven" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RAPNoticeGivnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bRentControlledByAgency" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bPetitionFiledPrviously" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PreviousCaseIDs" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="bLostService" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bSeriousProblem" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TenantPetitionInfo_TenantProblemInfo" Member="TenantProblemInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantProblemInfo" />
      <Association Name="TenantPetitionInfo_TenantLostServiceInfo" Member="TenantLostServiceInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantLostServiceInfo" />
      <Association Name="TenantPetitionInfo_TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionGroundInfo" />
      <Association Name="TenantPetitionInfo_TenantRentalIncrementInfo" Member="TenantRentalIncrementInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantRentalIncrementInfo" />
      <Association Name="UnitType_TenantPetitionInfo" Member="UnitType" ThisKey="UnitTypeID" OtherKey="UnitTypeID" Type="UnitType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantRentalIncrementInfo" Member="TenantRentalIncrementInfos">
    <Type Name="TenantRentalIncrementInfo">
      <Column Name="RentalIncreaseInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bRentIncreaseNoticeGiven" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentIncreaseNoticeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreaseEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreasedFrom" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="RentIncreasedTo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="bRentIncreaseContested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TenantPetitionInfo_TenantRentalIncrementInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppealGrounds" Member="AppealGrounds">
    <Type Name="AppealGround">
      <Column Name="AppealGroundID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppealDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="AppealGround_TenantAppealGroundInfo" Member="TenantAppealGroundInfos" ThisKey="AppealGroundID" OtherKey="AppealGroundID" Type="TenantAppealGroundInfo" />
    </Type>
  </Table>
  <Table Name="dbo.CaseDetails" Member="CaseDetails">
    <Type Name="CaseDetail">
      <Column Name="C_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CaseID" Type="System.String" DbType="VarChar(8)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PetitionFileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenantAppealID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PetitionCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenantUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bThirdPartyRepresentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bAgreeToCityMediation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CaseFiledBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bCaseFiledByThirdParty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CaseAssignedTo" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CityUserFirstName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CityUserLastName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="CityUserMailID" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="WorlFlowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HearingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AppealDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TenantAppealDetail_CaseDetail" Member="TenantAppealDetail" ThisKey="TenantAppealID" OtherKey="TenantAppealID" Type="TenantAppealDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantAppealDetails" Member="TenantAppealDetails">
    <Type Name="TenantAppealDetail">
      <Column Name="TenantAppealID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bThirdPartyRepresentation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpposingPartyCommunicateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AppealFiledBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TenantAppealDetail_CaseDetail" Member="CaseDetails" ThisKey="TenantAppealID" OtherKey="TenantAppealID" Type="CaseDetail" />
    </Type>
  </Table>
  <Table Name="dbo.TenantAppealGroundInfo" Member="TenantAppealGroundInfos">
    <Type Name="TenantAppealGroundInfo">
      <Column Name="TenantAppealGroudID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppealID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppealGroundID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AppealGround_TenantAppealGroundInfo" Member="AppealGround" ThisKey="AppealGroundID" OtherKey="AppealGroundID" Type="AppealGround" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppealOpposingParty" Member="AppealOpposingParties">
    <Type Name="AppealOpposingParty">
      <Column Name="AppealOpposingPartyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppealID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpposingPartyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>