<?xml version="1.0" encoding="utf-8"?><Database Name="OAKRAP" Class="ApplicationProcessingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ev-sql-dev;Initial Catalog=OAKRAP;Integrated Security=True" SettingsObjectName="RAP.DAL.Properties.Settings" SettingsPropertyName="OAKRAPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CurrentOnRentStatus" Member="CurrentOnRentStatus">
    <Type Name="CurrentOnRentStatus">
      <Column Name="RentStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RentStatus" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="CurrentOnRentStatus_OwnerPetitionPropertyInfo" Member="OwnerPetitionPropertyInfos" ThisKey="RentStatusID" OtherKey="RentStatusID" Type="OwnerPetitionPropertyInfo" />
    </Type>
  </Table>
  <Table Name="dbo.PetitionGrounds" Member="PetitionGrounds">
    <Type Name="PetitionGround">
      <Column Name="PetitionGroundID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PetitionDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="PetitionGround_TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos" ThisKey="PetitionGroundID" OtherKey="PetitionGroundID" Type="TenantPetitionGroundInfo" />
    </Type>
  </Table>
  <Table Name="dbo.UnitType" Member="UnitTypes">
    <Type Name="UnitType">
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="UnitType_OwnerPetitionPropertyInfo" Member="OwnerPetitionPropertyInfos" ThisKey="UnitTypeID" OtherKey="UnitTypeID" Type="OwnerPetitionPropertyInfo" />
      <Association Name="UnitType_OwnerResponsePropertyInfo" Member="OwnerResponsePropertyInfos" ThisKey="UnitTypeID" OtherKey="UnitTypeID" Type="OwnerResponsePropertyInfo" />
    </Type>
  </Table>
  <Table Name="dbo.TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos">
    <Type Name="TenantPetitionGroundInfo">
      <Column Name="TenantPetitionGroudID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PetitionGroundID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PetitionGround_TenantPetitionGroundInfo" Member="PetitionGround" ThisKey="PetitionGroundID" OtherKey="PetitionGroundID" Type="PetitionGround" IsForeignKey="true" />
      <Association Name="TenantPetitionInfo_TenantPetitionGroundInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantRentalIncrementInfo" Member="TenantRentalIncrementInfos">
    <Type Name="TenantRentalIncrementInfo">
      <Column Name="RentalIncreaseInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bRentIncreaseNoticeGiven" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentIncreaseNoticeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreaseEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreasedFrom" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="RentIncreasedTo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="bRentIncreaseContested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TenantPetitionInfo_TenantRentalIncrementInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppealGrounds" Member="AppealGrounds">
    <Type Name="AppealGround">
      <Column Name="AppealGroundID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppealDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="AppealGround_TenantAppealGroundInfo" Member="TenantAppealGroundInfos" ThisKey="AppealGroundID" OtherKey="AppealGroundID" Type="TenantAppealGroundInfo" />
    </Type>
  </Table>
  <Table Name="dbo.TenantAppealGroundInfo" Member="TenantAppealGroundInfos">
    <Type Name="TenantAppealGroundInfo">
      <Column Name="TenantAppealGroudID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppealID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppealGroundID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AppealGround_TenantAppealGroundInfo" Member="AppealGround" ThisKey="AppealGroundID" OtherKey="AppealGroundID" Type="AppealGround" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerPetitionTenantInfo" Member="OwnerPetitionTenantInfos">
    <Type Name="OwnerPetitionTenantInfo">
      <Column Name="TenantInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerPropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenantUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="OwnerPetitionPropertyInfo_OwnerPetitionTenantInfo" Member="OwnerPetitionPropertyInfo" ThisKey="OwnerPropertyID" OtherKey="OwnerPropertyID" Type="OwnerPetitionPropertyInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerRentIncreaseReasons" Member="OwnerRentIncreaseReasons">
    <Type Name="OwnerRentIncreaseReason">
      <Column Name="ReasonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="OwnerRentIncreaseReason_OwnerRentIncreaseReasonInfo" Member="OwnerRentIncreaseReasonInfos" ThisKey="ReasonID" OtherKey="ReasonID" Type="OwnerRentIncreaseReasonInfo" />
      <Association Name="OwnerRentIncreaseReason_OwnerResponseRentIncreaseReasonInfo" Member="OwnerResponseRentIncreaseReasonInfos" ThisKey="ReasonID" OtherKey="ReasonID" Type="OwnerResponseRentIncreaseReasonInfo" />
    </Type>
  </Table>
  <Table Name="dbo.PetitionDetails" Member="PetitionDetails">
    <Type Name="PetitionDetail">
      <Column Name="PetitionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerPetitionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PetitionDetail_CaseDetail" Member="CaseDetails" ThisKey="PetitionID" OtherKey="PetitionID" Type="CaseDetail" />
    </Type>
  </Table>
  <Table Name="dbo.PetitionCategory" Member="PetitionCategories">
    <Type Name="PetitionCategory">
      <Column Name="PetitionCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PetitionCategory" Member="PetitionCategory1" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="PetitionCategory_CaseDetail" Member="CaseDetails" ThisKey="PetitionCategoryID" OtherKey="PetitionCategoryID" Type="CaseDetail" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerRentIncreaseReasonInfo" Member="OwnerRentIncreaseReasonInfos">
    <Type Name="OwnerRentIncreaseReasonInfo">
      <Column Name="RentIncreaseReasonInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerPetitionApplicantInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReasonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="OwnerRentIncreaseReason_OwnerRentIncreaseReasonInfo" Member="OwnerRentIncreaseReason" ThisKey="ReasonID" OtherKey="ReasonID" Type="OwnerRentIncreaseReason" IsForeignKey="true" />
      <Association Name="OwnerPetitionApplicantInfo_OwnerRentIncreaseReasonInfo" Member="OwnerPetitionApplicantInfo" ThisKey="OwnerPetitionApplicantInfoID" OtherKey="OwnerPetitionApplicantInfoID" Type="OwnerPetitionApplicantInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NumberRangeForUnits" Member="NumberRangeForUnits">
    <Type Name="NumberRangeForUnit">
      <Column Name="RangeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RangeDesc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NumberRangeForUnit_TenantPetitionInfo" Member="TenantPetitionInfos" ThisKey="RangeID" OtherKey="RangeID" Type="TenantPetitionInfo" />
      <Association Name="NumberRangeForUnit_TenantResponseApplicationInfo" Member="TenantResponseApplicationInfos" ThisKey="RangeID" OtherKey="RangeID" Type="TenantResponseApplicationInfo" />
    </Type>
  </Table>
  <Table Name="dbo.TenantRentalHistory" Member="TenantRentalHistories">
    <Type Name="TenantRentalHistory">
      <Column Name="TenantRentalHistoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoveInDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InitialRent" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="bRAPNoticeGiven" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RAPNoticeGivenDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="bRentControlledByAgency" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PreviousCaseIDs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TenantPetitionInfo_TenantRentalHistory" Member="TenantPetitionInfo" ThisKey="PetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantProblemInfo" Member="TenantProblemInfos">
    <Type Name="TenantProblemInfo">
      <Column Name="ProblemInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProblemDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EstimatedLoss" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="ProblemBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TenantPetitionInfo_TenantProblemInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantLostServiceInfo" Member="TenantLostServiceInfos">
    <Type Name="TenantLostServiceInfo">
      <Column Name="LostServiceInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReducedServiceDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EstimatedLoss" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="LossBeganDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TenantPetitionInfo_TenantLostServiceInfo" Member="TenantPetitionInfo" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerPetitionRentalIncrementInfo" Member="OwnerPetitionRentalIncrementInfos">
    <Type Name="OwnerPetitionRentalIncrementInfo">
      <Column Name="RentalIncreaseInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerPropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bRentIncreaseNoticeGiven" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentIncreaseNoticeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreaseEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreasedFrom" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="RentIncreasedTo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Association Name="OwnerPetitionPropertyInfo_OwnerPetitionRentalIncrementInfo" Member="OwnerPetitionPropertyInfo" ThisKey="OwnerPropertyID" OtherKey="OwnerPropertyID" Type="OwnerPetitionPropertyInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RAPNoticeStatus" Member="RAPNoticeStatus">
    <Type Name="RAPNoticeStatus">
      <Column Name="RAPNoticeStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RAPNoticeStatus" Member="RAPNoticeStatus1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerPetitionApplicantInfo" Member="OwnerPetitionApplicantInfos">
    <Type Name="OwnerPetitionApplicantInfo">
      <Column Name="OwnerPetitionApplicantInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicantUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bThirdPartyRepresentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bBusinessLicensePaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BusinessLicenseNumber" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="bRentAdjustmentProgramFeePaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BuildingAcquiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberOfUnits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bMoreThanOneStreetOnParcel" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bPetitionFiled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="OwnerPetitionApplicantInfo_OwnerRentIncreaseReasonInfo" Member="OwnerRentIncreaseReasonInfos" ThisKey="OwnerPetitionApplicantInfoID" OtherKey="OwnerPetitionApplicantInfoID" Type="OwnerRentIncreaseReasonInfo" />
      <Association Name="OwnerPetitionApplicantInfo_OwnerPetitionInfo" Member="OwnerPetitionInfos" ThisKey="OwnerPetitionApplicantInfoID" OtherKey="OwnerPetitionApplicantInfoID" Type="OwnerPetitionInfo" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerPetitionPropertyInfo" Member="OwnerPetitionPropertyInfos">
    <Type Name="OwnerPetitionPropertyInfo">
      <Column Name="OwnerPropertyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MovedInDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InitialRent" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="RAPNoticeGivenDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bPetitionFiled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RAPNoticeStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OwnerPetitionPropertyInfo_OwnerPetitionTenantInfo" Member="OwnerPetitionTenantInfos" ThisKey="OwnerPropertyID" OtherKey="OwnerPropertyID" Type="OwnerPetitionTenantInfo" />
      <Association Name="OwnerPetitionPropertyInfo_OwnerPetitionRentalIncrementInfo" Member="OwnerPetitionRentalIncrementInfos" ThisKey="OwnerPropertyID" OtherKey="OwnerPropertyID" Type="OwnerPetitionRentalIncrementInfo" />
      <Association Name="OwnerPetitionPropertyInfo_OwnerPetitionInfo" Member="OwnerPetitionInfos" ThisKey="OwnerPropertyID" OtherKey="OwnerPropertyID" Type="OwnerPetitionInfo" />
      <Association Name="CurrentOnRentStatus_OwnerPetitionPropertyInfo" Member="CurrentOnRentStatus" ThisKey="RentStatusID" OtherKey="RentStatusID" Type="CurrentOnRentStatus" IsForeignKey="true" />
      <Association Name="UnitType_OwnerPetitionPropertyInfo" Member="UnitType" ThisKey="UnitTypeID" OtherKey="UnitTypeID" Type="UnitType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerPetitionInfo" Member="OwnerPetitionInfos">
    <Type Name="OwnerPetitionInfo">
      <Column Name="OwnerPetitionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerPetitionApplicantInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerPropertyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bPetitionFiledByThirdParty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bAgreeToCityMediation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="OwnerPetitionApplicantInfo_OwnerPetitionInfo" Member="OwnerPetitionApplicantInfo" ThisKey="OwnerPetitionApplicantInfoID" OtherKey="OwnerPetitionApplicantInfoID" Type="OwnerPetitionApplicantInfo" IsForeignKey="true" />
      <Association Name="OwnerPetitionPropertyInfo_OwnerPetitionInfo" Member="OwnerPetitionPropertyInfo" ThisKey="OwnerPropertyID" OtherKey="OwnerPropertyID" Type="OwnerPetitionPropertyInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerPetitionPageSubmissionStatus" Member="OwnerPetitionPageSubmissionStatus">
    <Type Name="OwnerPetitionPageSubmissionStatus">
      <Column Name="NavigationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImportantInformation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ApplicantInformation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="JustificationForRentIncrease" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentalProperty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentHistory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdditionalDocumentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Review" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Verification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantPetitionPageSubmissionStatus" Member="TenantPetitionPageSubmissionStatus">
    <Type Name="TenantPetitionPageSubmissionStatus">
      <Column Name="NavigationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImportantInformation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ApplicantInformation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GroundsForPetition" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentHistory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LostService" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdditionalDocumentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Review" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Verification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServeAppeal" Member="ServeAppeals">
    <Type Name="ServeAppeal">
      <Column Name="AppealServeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppealID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bAcknowledgeNamePin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bThirdParty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bDeclaration" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PenaltyDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppealOpposingParty" Member="AppealOpposingParties">
    <Type Name="AppealOpposingParty">
      <Column Name="AppealOpposingPartyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppealID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpposingPartyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantAppealDetails" Member="TenantAppealDetails">
    <Type Name="TenantAppealDetail">
      <Column Name="AppealID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bThirdPartyRepresentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OpposingPartyCommunicateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AppealFiledBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CaseNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AppealCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsSubmitted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ApplicantUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AppealDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TenantAppealDetail_CaseDetail" Member="CaseDetails" ThisKey="AppealID" OtherKey="TenantAppealID" Type="CaseDetail" />
    </Type>
  </Table>
  <Table Name="dbo.TenantPetitionInfo" Member="TenantPetitionInfos">
    <Type Name="TenantPetitionInfo">
      <Column Name="TenantPetitionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicantUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bThirdPartyRepresentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OwnerUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyManagerUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberOfUnits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RangeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bRentStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProvideExplanation" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PetitionFiledBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsSubmitted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TenantPetitionInfo_TenantPetitionGroundInfo" Member="TenantPetitionGroundInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionGroundInfo" />
      <Association Name="TenantPetitionInfo_TenantRentalIncrementInfo" Member="TenantRentalIncrementInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantRentalIncrementInfo" />
      <Association Name="TenantPetitionInfo_TenantRentalHistory" Member="TenantRentalHistories" ThisKey="TenantPetitionID" OtherKey="PetitionID" Type="TenantRentalHistory" />
      <Association Name="TenantPetitionInfo_TenantProblemInfo" Member="TenantProblemInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantProblemInfo" />
      <Association Name="TenantPetitionInfo_TenantLostServiceInfo" Member="TenantLostServiceInfos" ThisKey="TenantPetitionID" OtherKey="TenantPetitionID" Type="TenantLostServiceInfo" />
      <Association Name="TenantPetitionInfo_TenantPetitionVerification" Member="TenantPetitionVerifications" ThisKey="TenantPetitionID" OtherKey="PetitionID" Type="TenantPetitionVerification" />
      <Association Name="NumberRangeForUnit_TenantPetitionInfo" Member="NumberRangeForUnit" ThisKey="RangeID" OtherKey="RangeID" Type="NumberRangeForUnit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantPetitionVerification" Member="TenantPetitionVerifications">
    <Type Name="TenantPetitionVerification">
      <Column Name="VerificationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bDeclarePenalty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bThirdParty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bThirdPartyMediation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bCaseMediation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="TenantPetitionInfo_TenantPetitionVerification" Member="TenantPetitionInfo" ThisKey="PetitionID" OtherKey="TenantPetitionID" Type="TenantPetitionInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantResponseVerification" Member="TenantResponseVerifications">
    <Type Name="TenantResponseVerification">
      <Column Name="VerificationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantResponseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bDeclarePenalty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bThirdParty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bThirdPartyMediation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bCaseMediation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="TenantResponseApplicationInfo_TenantResponseVerification" Member="TenantResponseApplicationInfo" ThisKey="TenantResponseID" OtherKey="TenantResponseID" Type="TenantResponseApplicationInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantResponseExemptContestedInfo" Member="TenantResponseExemptContestedInfos">
    <Type Name="TenantResponseExemptContestedInfo">
      <Column Name="ExemptContestedID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantResponseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Explaination" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="TenantResponseApplicationInfo_TenantResponseExemptContestedInfo" Member="TenantResponseApplicationInfo" ThisKey="TenantResponseID" OtherKey="TenantResponseID" Type="TenantResponseApplicationInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantResponseRentalHistory" Member="TenantResponseRentalHistories">
    <Type Name="TenantResponseRentalHistory">
      <Column Name="TenantResponseRentalHistoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantResponseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoveInDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InitialRent" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="bRAPNoticeGiven" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RAPNoticeGivenDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TenantResponseApplicationInfo_TenantResponseRentalHistory" Member="TenantResponseApplicationInfo" ThisKey="TenantResponseID" OtherKey="TenantResponseID" Type="TenantResponseApplicationInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantResponseRentalIncrementInfo" Member="TenantResponseRentalIncrementInfos">
    <Type Name="TenantResponseRentalIncrementInfo">
      <Column Name="RentalIncreaseInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenantResponseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bRentIncreaseNoticeGiven" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentIncreaseNoticeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreaseEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreasedFrom" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="RentIncreasedTo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TenantResponseApplicationInfo_TenantResponseRentalIncrementInfo" Member="TenantResponseApplicationInfo" ThisKey="RentalIncreaseInfoID" OtherKey="TenantResponseID" Type="TenantResponseApplicationInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantResponseApplicationInfo" Member="TenantResponseApplicationInfos">
    <Type Name="TenantResponseApplicationInfo">
      <Column Name="TenantResponseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="C_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplicantUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bThirdPartyRepresentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OwnerUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyManagerUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberOfUnits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RangeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bRentStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProvideExplanation" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResponseFiledBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsSubmitted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TenantResponseApplicationInfo_TenantResponseVerification" Member="TenantResponseVerifications" ThisKey="TenantResponseID" OtherKey="TenantResponseID" Type="TenantResponseVerification" />
      <Association Name="TenantResponseApplicationInfo_TenantResponseExemptContestedInfo" Member="TenantResponseExemptContestedInfos" ThisKey="TenantResponseID" OtherKey="TenantResponseID" Type="TenantResponseExemptContestedInfo" />
      <Association Name="TenantResponseApplicationInfo_TenantResponseRentalHistory" Member="TenantResponseRentalHistories" ThisKey="TenantResponseID" OtherKey="TenantResponseID" Type="TenantResponseRentalHistory" />
      <Association Name="TenantResponseApplicationInfo_TenantResponseRentalIncrementInfo" Member="TenantResponseRentalIncrementInfo" ThisKey="TenantResponseID" OtherKey="RentalIncreaseInfoID" Type="TenantResponseRentalIncrementInfo" Cardinality="One" />
      <Association Name="NumberRangeForUnit_TenantResponseApplicationInfo" Member="NumberRangeForUnit" ThisKey="RangeID" OtherKey="RangeID" Type="NumberRangeForUnit" IsForeignKey="true" />
      <Association Name="CaseDetail_TenantResponseApplicationInfo" Member="CaseDetail" ThisKey="C_ID" OtherKey="C_ID" Type="CaseDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenantResponsePageSubmissionStatus" Member="TenantResponsePageSubmissionStatus">
    <Type Name="TenantResponsePageSubmissionStatus">
      <Column Name="NavigationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenantResponseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportantInformation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ApplicantInformation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExemptionContested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentHistory" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdditionalDocumentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Review" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Verification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerResponseApplicantInfo" Member="OwnerResponseApplicantInfos">
    <Type Name="OwnerResponseApplicantInfo">
      <Column Name="OwnerResponseApplicantInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicantUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bThirdPartyRepresentation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThirdPartyUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bBusinessLicensePaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BusinessLicenseNumber" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="bRentAdjustmentProgramFeePaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BuildingAcquiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberOfUnits" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bMoreThanOneStreetOnParcel" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bPetitionFiled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ResponseFiledByThirdParty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CaseRespondingTo" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerResponseTenantInfo" Member="OwnerResponseTenantInfos">
    <Type Name="OwnerResponseTenantInfo">
      <Column Name="TenantInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenantUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="OwnerResponsePropertyInfo_OwnerResponseTenantInfo" Member="OwnerResponsePropertyInfo" ThisKey="PropertyID" OtherKey="PropertyID" Type="OwnerResponsePropertyInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerResponseRentalIncrementInfo" Member="OwnerResponseRentalIncrementInfos">
    <Type Name="OwnerResponseRentalIncrementInfo">
      <Column Name="RentalIncreaseInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bRentIncreaseNoticeGiven" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RentIncreaseNoticeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreaseEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RentIncreasedFrom" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="RentIncreasedTo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Association Name="OwnerResponseRentalIncrementInfo_OwnerResponseRentIncreaseReasonInfo" Member="OwnerResponseRentIncreaseReasonInfos" ThisKey="RentalIncreaseInfoID" OtherKey="RentalIncreaseInfoID" Type="OwnerResponseRentIncreaseReasonInfo" />
      <Association Name="OwnerResponsePropertyInfo_OwnerResponseRentalIncrementInfo" Member="OwnerResponsePropertyInfo" ThisKey="PropertyID" OtherKey="PropertyID" Type="OwnerResponsePropertyInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerResponsePropertyInfo" Member="OwnerResponsePropertyInfos">
    <Type Name="OwnerResponsePropertyInfo">
      <Column Name="PropertyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovedInDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InitialRent" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="RAPNoticeGivenDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bCapitalImprovementIncrease" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bCaptialImprovementContested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CaseNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bRAPNoticeToRAPOffice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RAPNoticeToRAPOfficeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bExemptFromRentAdjustment" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bPriorTenantLeftAfteQuitNotice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PriorTenantLeftAfteQuitNotice" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="bPriorTenantLeftAfteRentIncreaseNotice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PriorTenantLeftAfteRentIncreaseNotice" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="bPriorTenantEvicted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PriorTenantEvicted" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="bSingleFamilyUnitOrCondominium" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SingleFamilyUnitOrCondominium" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="bRoommatesWhenMoviedIN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RoommatesWhenMoviedIN" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="bUnitPruchased" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UnitPruchased" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PurchasedFrom" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bEntireBuildingPurchased" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EntireBuildingPurchased" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bPetitionFiled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentOnRent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RAPNoticeStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OwnerResponsePropertyInfo_OwnerResponseTenantInfo" Member="OwnerResponseTenantInfos" ThisKey="PropertyID" OtherKey="PropertyID" Type="OwnerResponseTenantInfo" />
      <Association Name="OwnerResponsePropertyInfo_OwnerResponseRentalIncrementInfo" Member="OwnerResponseRentalIncrementInfos" ThisKey="PropertyID" OtherKey="PropertyID" Type="OwnerResponseRentalIncrementInfo" />
      <Association Name="UnitType_OwnerResponsePropertyInfo" Member="UnitType" ThisKey="UnitTypeID" OtherKey="UnitTypeID" Type="UnitType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OwnerResponseRentIncreaseReasonInfo" Member="OwnerResponseRentIncreaseReasonInfos">
    <Type Name="OwnerResponseRentIncreaseReasonInfo">
      <Column Name="RentIncreaseReasonInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RentalIncreaseInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReasonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="OwnerRentIncreaseReason_OwnerResponseRentIncreaseReasonInfo" Member="OwnerRentIncreaseReason" ThisKey="ReasonID" OtherKey="ReasonID" Type="OwnerRentIncreaseReason" IsForeignKey="true" />
      <Association Name="OwnerResponseRentalIncrementInfo_OwnerResponseRentIncreaseReasonInfo" Member="OwnerResponseRentalIncrementInfo" ThisKey="RentalIncreaseInfoID" OtherKey="RentalIncreaseInfoID" Type="OwnerResponseRentalIncrementInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CaseDetails" Member="CaseDetails">
    <Type Name="CaseDetail">
      <Column Name="C_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CaseID" Type="System.String" DbType="VarChar(8)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PetitionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenantAppealID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PetitionCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenantResponseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerResponseID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseFiledBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bCaseFiledByThirdParty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HearingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AppealDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HearingOfficerUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CityAnalystUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CaseDetail_TenantResponseApplicationInfo" Member="TenantResponseApplicationInfos" ThisKey="C_ID" OtherKey="C_ID" Type="TenantResponseApplicationInfo" />
      <Association Name="TenantAppealDetail_CaseDetail" Member="TenantAppealDetail" ThisKey="TenantAppealID" OtherKey="AppealID" Type="TenantAppealDetail" IsForeignKey="true" />
      <Association Name="PetitionCategory_CaseDetail" Member="PetitionCategory" ThisKey="PetitionCategoryID" OtherKey="PetitionCategoryID" Type="PetitionCategory" IsForeignKey="true" />
      <Association Name="PetitionDetail_CaseDetail" Member="PetitionDetail" ThisKey="PetitionID" OtherKey="PetitionID" Type="PetitionDetail" IsForeignKey="true" />
    </Type>
  </Table>
</Database>