<?xml version="1.0" encoding="utf-8"?><Database Name="OAKRAP" Class="CommonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ev-sql-dev;Initial Catalog=OAKRAP;Integrated Security=True" SettingsObjectName="RAP.DAL.Properties.Settings" SettingsPropertyName="OAKRAPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateCode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ErrorLog" Member="ErrorLogs">
    <Type Name="ErrorLog">
      <Column Name="ErrorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ErrorNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ErrorMessageDetails" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DocDescriptions" Member="DocDescriptions">
    <Type Name="DocDescription">
      <Column Name="DescriptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelAddress" Member="ParcelAddresses">
    <Type Name="ParcelAddress">
      <Column Name="ParcelAddressID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="APNNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="UserInfo_ParcelAddress" Member="UserInfo" ThisKey="UserID" OtherKey="UserID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomEmailNotificationAttachments" Member="CustomEmailNotificationAttachments">
    <Type Name="CustomEmailNotificationAttachment">
      <Column Name="NotificationAttachmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NotificationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Document_CustomEmailNotificationAttachment" Member="Document" ThisKey="DocumentID" OtherKey="DocID" Type="Document" IsForeignKey="true" />
      <Association Name="CustomEmailNotification_CustomEmailNotificationAttachment" Member="CustomEmailNotification" ThisKey="NotificationID" OtherKey="NotificationID" Type="CustomEmailNotification" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MailNotificationAttachments" Member="MailNotificationAttachments">
    <Type Name="MailNotificationAttachment">
      <Column Name="NotificationAttachmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NotificationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MailNotification_MailNotificationAttachment" Member="MailNotification" ThisKey="NotificationID" OtherKey="NotificationID" Type="MailNotification" IsForeignKey="true" />
      <Association Name="Document_MailNotificationAttachment" Member="Document" ThisKey="DocumentID" OtherKey="DocID" Type="Document" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MailNotification" Member="MailNotifications">
    <Type Name="MailNotification">
      <Column Name="NotificationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Activity" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Recipient" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="MailingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="C_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MailNotification_MailNotificationAttachment" Member="MailNotificationAttachments" ThisKey="NotificationID" OtherKey="NotificationID" Type="MailNotificationAttachment" />
    </Type>
  </Table>
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Document">
      <Column Name="DocID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DocCategory" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="DocTitle" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="DocDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DocThirdPartyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="C_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsPetitionFiled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MimeType" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CityUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Document_CustomEmailNotificationAttachment" Member="CustomEmailNotificationAttachments" ThisKey="DocID" OtherKey="DocumentID" Type="CustomEmailNotificationAttachment" />
      <Association Name="Document_MailNotificationAttachment" Member="MailNotificationAttachments" ThisKey="DocID" OtherKey="DocumentID" Type="MailNotificationAttachment" />
    </Type>
  </Table>
  <Table Name="dbo.CustomEmailNotification" Member="CustomEmailNotifications">
    <Type Name="CustomEmailNotification">
      <Column Name="NotificationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Recipient" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="CC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BCC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MessageBody" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="C_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CustomEmailNotification_CustomEmailNotificationAttachment" Member="CustomEmailNotificationAttachments" ThisKey="NotificationID" OtherKey="NotificationID" Type="CustomEmailNotificationAttachment" />
    </Type>
  </Table>
  <Table Name="dbo.UserInfo" Member="UserInfos">
    <Type Name="UserInfo">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="BusinessName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ContactEmail" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="bParcelAddress" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="UserInfo_ParcelAddress" Member="ParcelAddresses" ThisKey="UserID" OtherKey="UserID" Type="ParcelAddress" />
    </Type>
  </Table>
</Database>