<?xml version="1.0" encoding="utf-8"?><Database Name="OAKRAP" Class="DashboardDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ev-sql-dev;Initial Catalog=OAKRAP;Integrated Security=True" SettingsObjectName="RAP.DAL.Properties.Settings" SettingsPropertyName="OAKRAPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Activity" Member="Activities">
    <Type Name="Activity">
      <Column Name="ActivityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActivityName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Activity_ActivityStatus" Member="ActivityStatus" ThisKey="ActivityID" OtherKey="ActivityID" Type="ActivityStatus" />
      <Association Name="Activity_CaseActivityStatus" Member="CaseActivityStatus" ThisKey="ActivityID" OtherKey="ActivityID" Type="CaseActivityStatus" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityStatus" Member="ActivityStatus">
    <Type Name="ActivityStatus">
      <Column Name="ActivityStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActivityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Activity_ActivityStatus" Member="Activity" ThisKey="ActivityID" OtherKey="ActivityID" Type="Activity" IsForeignKey="true" />
      <Association Name="Status_ActivityStatus" Member="Status" ThisKey="StatusID" OtherKey="StatusID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusDesc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Status_ActivityStatus" Member="ActivityStatus" ThisKey="StatusID" OtherKey="StatusID" Type="ActivityStatus" />
      <Association Name="Status_CaseActivityStatus" Member="CaseActivityStatus" ThisKey="StatusID" OtherKey="StatusID" Type="CaseActivityStatus" />
    </Type>
  </Table>
  <Table Name="dbo.CaseActivityStatus" Member="CaseActivityStatus">
    <Type Name="CaseActivityStatus">
      <Column Name="CaseActivityStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="C_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Activity_CaseActivityStatus" Member="Activity" ThisKey="ActivityID" OtherKey="ActivityID" Type="Activity" IsForeignKey="true" />
      <Association Name="Status_CaseActivityStatus" Member="Status" ThisKey="StatusID" OtherKey="StatusID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReturnCaseSearch" Member="ReturnCaseSearches">
    <Type Name="ReturnCaseSearch" Id="ID1">
      <Column Name="RankNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="C_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ActivityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivityName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Analyst" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HearingOfficer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TenantName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplicantAddressLine1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplicantAddressLine2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplicantCity" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplicantStateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplicantStateCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ApplicantZip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="OwnerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OPOwnerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OPAddressLine1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OPAddressLine2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OPCity" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OPStateCode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="OPOwnerZip" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="OwnerTenantName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PetitionCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.USP_Status_Get" Method="USP_Status_Get">
    <Parameter Name="ActivityID" Parameter="activityID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="VarChar(MAX)" Direction="InOut" />
    <Parameter Name="errorCode" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="USP_Status_GetResult">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.USP_NewActivityStatus_Save" Method="USP_NewActivityStatus_Save">
    <Parameter Name="ActivityID" Parameter="activityID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StatusID" Parameter="statusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="C_ID" Parameter="c_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="CreatedDate" Parameter="createdDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.Int32" DbType="Int" />
    <Parameter Name="CreatedByAcctType" Parameter="createdByAcctType" Type="System.Int32" DbType="Int" />
    <Parameter Name="NotificationID" Parameter="notificationID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NotificationType" Parameter="notificationType" Type="System.Int32" DbType="Int" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="VarChar(MAX)" Direction="InOut" />
    <Parameter Name="errorCode" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.USP_ActivityStatusForCase_Get" Method="USP_ActivityStatusForCase_Get">
    <Parameter Name="C_ID" Parameter="c_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="VarChar(MAX)" Direction="InOut" />
    <Parameter Name="errorCode" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="USP_ActivityStatusForCase_GetResult">
      <Column Name="ActivityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="CustName" Type="System.String" DbType="VarChar(51)" CanBeNull="true" />
      <Column Name="NotificationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NotificationType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.USP_SearchCase_Get" Method="USP_SearchCase_Get">
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="APNNumber" Parameter="aPNNumber" Type="System.Int32" DbType="Int" />
    <Parameter Name="AnalystID" Parameter="analystID" Type="System.Int32" DbType="Int" />
    <Parameter Name="HearingOfficerID" Parameter="hearingOfficerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AddressLine1" Parameter="addressLine1" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="AddressLine2" Parameter="addressLine2" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="PhoneNumber" Parameter="phoneNumber" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="CaseNumber" Parameter="caseNumber" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="CaseStatus" Parameter="caseStatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="SortBy" Parameter="sortBy" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortReverse" Parameter="sortReverse" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentPage" Parameter="currentPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalCount" Parameter="totalCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="VarChar(MAX)" Direction="InOut" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.USP_GetCase_NoAnalyst" Method="USP_GetCase_NoAnalyst">
    <Parameter Name="SortBy" Parameter="sortBy" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SortReverse" Parameter="sortReverse" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentPage" Parameter="currentPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalCount" Parameter="totalCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="VarChar(MAX)" Direction="InOut" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>